local config = require("nightfox.config").options
local util = require("nightfox.util")

local fmt = string.format

local header = [[
-- This file is autogenerated by NIGHTFOX. 
-- Do not make changes directly to this file.
]]

local vim_highlight_func = [[
local function highlight(list)
  local cmds = {}
  for group, opts in pairs(list) do
    table.insert(cmds, string.format(
      "highlight %s guifg=%s guibg=%s gui=%s guisp=%s",
      group,
      opts.fg or "NONE",
      opts.bg or "NONE",
      opts.style or "NONE",
      opts.sp or "NONE"
    ))
  end
  vim.cmd(table.concat(cmds, "\n"))
end
]]

local vim_link_func = [[
local function link(list)
  local cmds = {}
  for group, opts in pairs(list) do
    table.insert(cmds, string.format("highlight! link %s %s", group, opts))
  end
  vim.cmd(table.concat(cmds, "\n"))
end
]]

local clear_func = [[
local function clear()
  if vim.g.colors_name then
    vim.cmd("hi clear")
  end
end
]]

local function gen_main_func()
  local lines = {}

  -- stylua: ignore
  table.insert(lines, [[
clear()
highlight(highlights)
link(links)
set_info()]])

  if config.terminal_colors then
    table.insert(lines, "set_terminal()")
  end

  return table.concat(lines, "\n")
end

local function gen_set_info_func(meta)
  local lines = {}
  table.insert(lines, "local function set_info()")

  local background = meta.light and "light" or "dark"
  table.insert(lines, [[  vim.cmd("set termguicolors")]])
  table.insert(lines, fmt([[  vim.cmd("set background=%s")]], background))
  table.insert(lines, fmt([[  vim.g.colors_name = "%s"]], meta.name))

  table.insert(lines, "end")
  table.insert(lines, "")

  return table.concat(lines, "\n")
end

local function gen_terminal_func(spec)
  local c = spec.pallet

  local lines = {}

  -- stylua: ignore
  local colors = {
    fmt([["%s"]], c.black.base),   fmt([["%s"]], c.red.base),
    fmt([["%s"]], c.green.base),   fmt([["%s"]], c.yellow.base),
    fmt([["%s"]], c.blue.base),    fmt([["%s"]], c.magenta.base),
    fmt([["%s"]], c.cyan.base),    fmt([["%s"]], c.white.base),
    fmt([["%s"]], c.black.bright), fmt([["%s"]], c.red.bright),
    fmt([["%s"]], c.green.bright), fmt([["%s"]], c.yellow.bright),
    fmt([["%s"]], c.blue.bright),  fmt([["%s"]], c.magenta.bright),
    fmt([["%s"]], c.cyan.bright),  fmt([["%s"]], c.white.bright),
  }

  table.insert(lines, "local function set_terminal()")
  table.insert(lines, "  local colors = {")
  table.insert(lines, fmt("    %s,", table.concat(colors, ", ")))
  table.insert(lines, "  }")

  -- stylua: ignore
  table.insert(lines, [[
  for i, c in ipairs(colors) do
    local n = "terminal_color_" .. i - 1
    vim.g[n] = c
  end
  if vim.fn.has("nvim") == 0 then
    vim.g.terminal_ansi_colors = vim.list(colors)
  end
end
]])

  return table.concat(lines, "\n")
end

local M = {}

function M.compile()
  local output_path = config.compile_path
  local file_suffix = config.compile_file_suffix

  util.ensure_dir(output_path)

  local specs = require("nightfox.spec").load()

  for specname, spec in pairs(specs) do
    local lines = { header }
    local hlgroups = {}
    local hllinks = {}

    local groups = require("nightfox.group").load(spec)
    for name, opts in pairs(groups) do
      if opts.link and opts.link ~= "" then
        table.insert(hllinks, fmt([[  %s = "%s",]], name, opts.link))
      else
        local rhs = {}
        for key, value in pairs(opts) do
          table.insert(rhs, fmt([[%s = "%s"]], key, value))
        end
        table.sort(rhs)
        table.insert(hlgroups, fmt([[  %s = { %s },]], name, table.concat(rhs, ", ")))
      end
    end

    -- Write highlight groups
    table.sort(hlgroups)
    table.insert(lines, [[local highlights = {]])
    table.insert(lines, table.concat(hlgroups, "\n"))
    table.insert(lines, [[}]])
    table.insert(lines, "")

    -- Write link groups
    table.sort(hllinks)
    table.insert(lines, [[local links = {]])
    table.insert(lines, table.concat(hllinks, "\n"))
    table.insert(lines, [[}]])
    table.insert(lines, "")

    -- Write helper functions
    table.insert(lines, vim_highlight_func)
    table.insert(lines, vim_link_func)
    table.insert(lines, clear_func)
    table.insert(lines, gen_set_info_func(spec.pallet.meta))

    if config.terminal_colors then
      table.insert(lines, gen_terminal_func(spec))
    end

    table.insert(lines, gen_main_func())

    local output_file = util.join_paths(output_path, specname .. file_suffix .. ".lua")
    local file = io.open(output_file, "w")
    file:write(table.concat(lines, "\n"))
    file:close()
  end
end

function M.clean()
  local foxes = require("nightfox.pallet").foxes

  local output_path = config.compile_path
  local file_suffix = config.compile_file_suffix

  for _, name in ipairs(foxes) do
    local output_file = util.join_paths(output_path, name .. file_suffix .. ".lua")
    os.remove(output_file)
  end
end

M.clean()

return M
