-- This file is autogenerated by NIGHTFOX.
-- Do not make changes directly to this file.

local cmd = vim.fn.has("nvim") == 0 and vim.command or vim.cmd

if vim.g.colors_name then
  cmd("hi clear")
end

cmd("set termguicolors")
cmd("set background=dark")
vim.g.colors_name = "duskfox"

cmd([[
highlight AerialGuide guifg=#39506d guibg=NONE gui=NONE guisp=NONE |
highlight Bold guifg=NONE guibg=NONE gui=bold guisp=NONE |
highlight BufferCurrent guifg=#A6A6A2 guibg=#71839b gui=NONE guisp=NONE |
highlight BufferCurrentIndex guifg=#6173d1 guibg=#71839b gui=NONE guisp=NONE |
highlight BufferCurrentMod guifg=#d9c679 guibg=#71839b gui=NONE guisp=NONE |
highlight BufferCurrentSign guifg=#6173d1 guibg=#71839b gui=NONE guisp=NONE |
highlight BufferCurrentTarget guifg=#b6776b guibg=#71839b gui=NONE guisp=NONE |
highlight BufferInactive guifg=#817c9c guibg=#192330 gui=NONE guisp=NONE |
highlight BufferInactiveIndex guifg=#817c9c guibg=#192330 gui=NONE guisp=NONE |
highlight BufferInactiveMod guifg=#394143 guibg=#192330 gui=NONE guisp=NONE |
highlight BufferInactiveSign guifg=#29394f guibg=#192330 gui=NONE guisp=NONE |
highlight BufferInactiveTarget guifg=#b6776b guibg=#192330 gui=NONE guisp=NONE |
highlight BufferTabpage guifg=#29394f guibg=#192330 gui=NONE guisp=NONE |
highlight BufferTabpages guifg=NONE guibg=#192330 gui=NONE guisp=NONE |
highlight BufferVisible guifg=#A6A6A2 guibg=#192330 gui=NONE guisp=NONE |
highlight BufferVisibleIndex guifg=#6173d1 guibg=#192330 gui=NONE guisp=NONE |
highlight BufferVisibleMod guifg=#d9c679 guibg=#192330 gui=NONE guisp=NONE |
highlight BufferVisibleSign guifg=#6173d1 guibg=#192330 gui=NONE guisp=NONE |
highlight BufferVisibleTarget guifg=#b6776b guibg=#192330 gui=NONE guisp=NONE |
highlight CmpDocumentation guifg=#A6A6A2 guibg=#192330 gui=NONE guisp=NONE |
highlight CmpDocumentationBorder guifg=#2b3b51 guibg=#192330 gui=NONE guisp=NONE |
highlight CmpItemAbbr guifg=#A6A6A2 guibg=NONE gui=NONE guisp=NONE |
highlight CmpItemAbbrDeprecated guifg=#71839b guibg=NONE gui=strikethrough guisp=NONE |
highlight CmpItemAbbrMatch guifg=#4ca585 guibg=NONE gui=NONE guisp=NONE |
highlight CmpItemAbbrMatchFuzzy guifg=#4ca585 guibg=NONE gui=NONE guisp=NONE |
highlight CmpItemKindDefault guifg=#B9B9B5 guibg=NONE gui=NONE guisp=NONE |
highlight CmpItemKindSnippet guifg=#B9B9B5 guibg=NONE gui=NONE guisp=NONE |
highlight ColorColumn guifg=NONE guibg=#212e3f gui=NONE guisp=NONE |
highlight Comment guifg=#817c9c guibg=NONE gui=NONE guisp=NONE |
highlight Conceal guifg=#39506d guibg=NONE gui=NONE guisp=NONE |
highlight Conditional guifg=#af8b6c guibg=NONE gui=NONE guisp=NONE |
highlight Constant guifg=#6173d1 guibg=NONE gui=NONE guisp=NONE |
highlight Cursor guifg=#1d2a39 guibg=#A6A6A2 gui=NONE guisp=NONE |
highlight CursorLine guifg=NONE guibg=#29394f gui=NONE guisp=NONE |
highlight CursorLineNr guifg=#d9c679 guibg=NONE gui=bold guisp=NONE |
highlight DapUIBreakpointsCurrentLine guifg=#4ca585 guibg=NONE gui=bold guisp=NONE |
highlight DapUIBreakpointsDisabledLine guifg=#817c9c guibg=NONE gui=NONE guisp=NONE |
highlight DapUIBreakpointsInfo guifg=#6173d1 guibg=NONE gui=NONE guisp=NONE |
highlight DapUIBreakpointsPath guifg=#78cad9 guibg=NONE gui=NONE guisp=NONE |
highlight DapUIDecoration guifg=#71839b guibg=NONE gui=NONE guisp=NONE |
highlight DapUIModifiedValue guifg=#dfcf8d guibg=NONE gui=bold guisp=NONE |
highlight DapUIScope guifg=#78cad9 guibg=NONE gui=NONE guisp=NONE |
highlight DapUIStoppedThread guifg=#78cad9 guibg=NONE gui=NONE guisp=NONE |
highlight DapUIValue guifg=#dfcf8d guibg=NONE gui=NONE guisp=NONE |
highlight DapUIVariable guifg=#dfcf8d guibg=NONE gui=NONE guisp=NONE |
highlight DapUIWatchesEmpty guifg=#b6776b guibg=NONE gui=NONE guisp=NONE |
highlight DapUIWatchesError guifg=#b6776b guibg=NONE gui=NONE guisp=NONE |
highlight DapUIWatchesValue guifg=#d9c679 guibg=NONE gui=NONE guisp=NONE |
highlight DashboardFooter guifg=#6173d1 guibg=NONE gui=italic guisp=NONE |
highlight DiagnosticError guifg=#b6776b guibg=NONE gui=NONE guisp=NONE |
highlight DiagnosticHint guifg=#4ca585 guibg=NONE gui=NONE guisp=NONE |
highlight DiagnosticInfo guifg=#6173d1 guibg=NONE gui=NONE guisp=NONE |
highlight DiagnosticUnderlineError guifg=NONE guibg=NONE gui=undercurl guisp=#b6776b |
highlight DiagnosticUnderlineHint guifg=NONE guibg=NONE gui=undercurl guisp=#4ca585 |
highlight DiagnosticUnderlineInfo guifg=NONE guibg=NONE gui=undercurl guisp=#6173d1 |
highlight DiagnosticUnderlineWarn guifg=NONE guibg=NONE gui=undercurl guisp=#d9c679 |
highlight DiagnosticVirtualTextError guifg=#b6776b guibg=#343640 gui=NONE guisp=NONE |
highlight DiagnosticVirtualTextHint guifg=#4ca585 guibg=#243c44 gui=NONE guisp=NONE |
highlight DiagnosticVirtualTextInfo guifg=#6173d1 guibg=#273550 gui=NONE guisp=NONE |
highlight DiagnosticVirtualTextWarn guifg=#d9c679 guibg=#394143 gui=NONE guisp=NONE |
highlight DiagnosticWarn guifg=#d9c679 guibg=NONE gui=NONE guisp=NONE |
highlight DiffAdd guifg=NONE guibg=#264348 gui=NONE guisp=NONE |
highlight DiffChange guifg=NONE guibg=#2b3957 gui=NONE guisp=NONE |
highlight DiffDelete guifg=NONE guibg=#3c3943 gui=NONE guisp=NONE |
highlight DiffText guifg=NONE guibg=#384776 gui=NONE guisp=NONE |
highlight Directory guifg=#4ca585 guibg=NONE gui=NONE guisp=NONE |
highlight EndOfBuffer guifg=#1d2a39 guibg=NONE gui=NONE guisp=NONE |
highlight Error guifg=#b6776b guibg=NONE gui=NONE guisp=NONE |
highlight ErrorMsg guifg=#b6776b guibg=NONE gui=NONE guisp=NONE |
highlight FernBranchText guifg=#6173d1 guibg=NONE gui=NONE guisp=NONE |
highlight FloatBorder guifg=#71839b guibg=NONE gui=NONE guisp=NONE |
highlight FoldColumn guifg=#71839b guibg=NONE gui=NONE guisp=NONE |
highlight Folded guifg=#71839b guibg=#212e3f gui=NONE guisp=NONE |
highlight Function guifg=#4ca585 guibg=NONE gui=NONE guisp=NONE |
highlight GitGutterAdd guifg=#4ca585 guibg=NONE gui=NONE guisp=NONE |
highlight GitGutterChange guifg=#d9c679 guibg=NONE gui=NONE guisp=NONE |
highlight GitGutterDelete guifg=#b6776b guibg=NONE gui=NONE guisp=NONE |
highlight GitSignsAdd guifg=#4ca585 guibg=NONE gui=NONE guisp=NONE |
highlight GitSignsChange guifg=#d9c679 guibg=NONE gui=NONE guisp=NONE |
highlight GitSignsDelete guifg=#b6776b guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette0 guifg=#2b2d35 guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette1 guifg=#b6776b guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette10 guifg=#67b397 guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette11 guifg=#dfcf8d guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette12 guifg=#7988d8 guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette13 guifg=#d5b192 guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette14 guifg=#78cad9 guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette15 guifg=#e2e1da guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette2 guifg=#4ca585 guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette3 guifg=#d9c679 guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette4 guifg=#6173d1 guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette5 guifg=#cea37f guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette6 guifg=#60c1d2 guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette7 guifg=#e2e1da guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette8 guifg=#4b4c53 guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette9 guifg=#c18b81 guibg=NONE gui=NONE guisp=NONE |
highlight HopNextKey guifg=#60c1d2 guibg=NONE gui=bold guisp=NONE |
highlight HopNextKey1 guifg=#6173d1 guibg=NONE gui=bold guisp=NONE |
highlight HopNextKey2 guifg=#5262b2 guibg=NONE gui=NONE guisp=NONE |
highlight HopUnmatched guifg=#817c9c guibg=NONE gui=NONE guisp=NONE |
highlight Identifier guifg=#60c1d2 guibg=NONE gui=NONE guisp=NONE |
highlight IncSearch guifg=#2b3b51 guibg=#4ca585 gui=NONE guisp=NONE |
highlight Italic guifg=NONE guibg=NONE gui=italic guisp=NONE |
highlight Keyword guifg=#cea37f guibg=NONE gui=NONE guisp=NONE |
highlight LightspeedGreyWash guifg=#817c9c guibg=NONE gui=NONE guisp=NONE |
highlight LineNr guifg=#71839b guibg=NONE gui=NONE guisp=NONE |
highlight LspCodeLens guifg=#817c9c guibg=NONE gui=NONE guisp=NONE |
highlight LspCodeLensSeparator guifg=#71839b guibg=NONE gui=NONE guisp=NONE |
highlight LspFloatWinBorder guifg=#71839b guibg=NONE gui=NONE guisp=NONE |
highlight LspFloatWinNormal guifg=NONE guibg=#192330 gui=NONE guisp=NONE |
highlight LspReferenceRead guifg=NONE guibg=#2b3b51 gui=NONE guisp=NONE |
highlight LspReferenceText guifg=NONE guibg=#2b3b51 gui=NONE guisp=NONE |
highlight LspReferenceWrite guifg=NONE guibg=#2b3b51 gui=NONE guisp=NONE |
highlight LspSagaCodeActionBorder guifg=#71839b guibg=NONE gui=NONE guisp=NONE |
highlight LspSagaDefPreviewBorder guifg=#71839b guibg=NONE gui=NONE guisp=NONE |
highlight LspSagaFinderSelection guifg=#2b3b51 guibg=NONE gui=NONE guisp=NONE |
highlight LspSagaHoverBorder guifg=#71839b guibg=NONE gui=NONE guisp=NONE |
highlight LspSagaRenameBorder guifg=#71839b guibg=NONE gui=NONE guisp=NONE |
highlight LspSagaSignatureHelpBorder guifg=#b6776b guibg=NONE gui=NONE guisp=NONE |
highlight LspSignatureActiveParameter guifg=#58658A guibg=NONE gui=NONE guisp=NONE |
highlight LspTroubleCount guifg=#cea37f guibg=#71839b gui=NONE guisp=NONE |
highlight LspTroubleNormal guifg=#71839b guibg=#192330 gui=NONE guisp=NONE |
highlight LspTroubleText guifg=#B9B9B5 guibg=NONE gui=NONE guisp=NONE |
highlight MatchParen guifg=#d9c679 guibg=NONE gui=bold guisp=NONE |
highlight ModeMsg guifg=#d9c679 guibg=NONE gui=bold guisp=NONE |
highlight ModesCopy guifg=NONE guibg=#d9c679 gui=NONE guisp=NONE |
highlight ModesDelete guifg=NONE guibg=#b6776b gui=NONE guisp=NONE |
highlight ModesInsert guifg=NONE guibg=#60c1d2 gui=NONE guisp=NONE |
highlight ModesVisual guifg=NONE guibg=#cea37f gui=NONE guisp=NONE |
highlight MoreMsg guifg=#6173d1 guibg=NONE gui=bold guisp=NONE |
highlight NeoTreeDirectoryIcon guifg=#6173d1 guibg=NONE gui=NONE guisp=NONE |
highlight NeoTreeDirectoryName guifg=#6173d1 guibg=NONE gui=NONE guisp=NONE |
highlight NeoTreeDotfile guifg=#5262b2 guibg=NONE gui=NONE guisp=NONE |
highlight NeoTreeFileName guifg=#B9B9B5 guibg=NONE gui=NONE guisp=NONE |
highlight NeoTreeFileNameOpened guifg=#A6A6A2 guibg=NONE gui=NONE guisp=NONE |
highlight NeoTreeGitAdded guifg=#4ca585 guibg=NONE gui=NONE guisp=NONE |
highlight NeoTreeGitConflict guifg=#d88e78 guibg=NONE gui=italic guisp=NONE |
highlight NeoTreeGitDeleted guifg=#b6776b guibg=NONE gui=NONE guisp=NONE |
highlight NeoTreeGitIgnored guifg=#817c9c guibg=NONE gui=NONE guisp=NONE |
highlight NeoTreeGitModified guifg=#d9c679 guibg=NONE gui=NONE guisp=NONE |
highlight NeoTreeGitUntracked guifg=#af8b6c guibg=NONE gui=NONE guisp=NONE |
highlight NeoTreeIndentMarker guifg=#39506d guibg=NONE gui=NONE guisp=NONE |
highlight NeoTreeNormal guifg=#A6A6A2 guibg=#192330 gui=NONE guisp=NONE |
highlight NeoTreeRootName guifg=#d88e78 guibg=NONE gui=bold guisp=NONE |
highlight NeoTreeSymbolicLinkTarget guifg=#4b7983 guibg=NONE gui=NONE guisp=NONE |
highlight NeogitBranch guifg=#d9c679 guibg=NONE gui=NONE guisp=NONE |
highlight NeogitDiffAdd guifg=#4ca585 guibg=NONE gui=NONE guisp=NONE |
highlight NeogitDiffAddHighlight guifg=NONE guibg=#264348 gui=NONE guisp=NONE |
highlight NeogitDiffContextHighlight guifg=NONE guibg=#2b3957 gui=NONE guisp=NONE |
highlight NeogitDiffDelete guifg=#b6776b guibg=NONE gui=NONE guisp=NONE |
highlight NeogitDiffDeleteHighlight guifg=NONE guibg=#3c3943 gui=NONE guisp=NONE |
highlight NeogitHunkHeader guifg=#6173d1 guibg=#29394f gui=NONE guisp=NONE |
highlight NeogitHunkHeaderHighlight guifg=#6173d1 guibg=#2b3b51 gui=NONE guisp=NONE |
highlight NeogitNotificationError guifg=#b6776b guibg=NONE gui=NONE guisp=NONE |
highlight NeogitNotificationInfo guifg=#6173d1 guibg=NONE gui=NONE guisp=NONE |
highlight NeogitNotificationWarning guifg=#d9c679 guibg=NONE gui=NONE guisp=NONE |
highlight NeogitRemote guifg=#4ca585 guibg=NONE gui=NONE guisp=NONE |
highlight NonText guifg=#39506d guibg=NONE gui=NONE guisp=NONE |
highlight Normal guifg=#A6A6A2 guibg=#1d2a39 gui=NONE guisp=NONE |
highlight NormalFloat guifg=#A6A6A2 guibg=#192330 gui=NONE guisp=NONE |
highlight NormalNC guifg=#A6A6A2 guibg=#1d2a39 gui=NONE guisp=NONE |
highlight NotifyDEBUGBorder guifg=#34685f guibg=NONE gui=NONE guisp=NONE |
highlight NotifyDEBUGTitle guifg=#4ca585 guibg=NONE gui=NONE guisp=NONE |
highlight NotifyERRORBorder guifg=#6a5052 guibg=NONE gui=NONE guisp=NONE |
highlight NotifyERRORTitle guifg=#b6776b guibg=NONE gui=NONE guisp=NONE |
highlight NotifyINFOBorder guifg=#3f4e85 guibg=NONE gui=NONE guisp=NONE |
highlight NotifyINFOTitle guifg=#6173d1 guibg=NONE gui=NONE guisp=NONE |
highlight NotifyTRACEBorder guifg=#39506d guibg=NONE gui=NONE guisp=NONE |
highlight NotifyTRACETitle guifg=#817c9c guibg=NONE gui=NONE guisp=NONE |
highlight NotifyWARNBorder guifg=#7b7859 guibg=NONE gui=NONE guisp=NONE |
highlight NotifyWARNTitle guifg=#d9c679 guibg=NONE gui=NONE guisp=NONE |
highlight Number guifg=#52a4b2 guibg=NONE gui=NONE guisp=NONE |
highlight NvimTreeEmptyFolderName guifg=#71839b guibg=NONE gui=NONE guisp=NONE |
highlight NvimTreeFolderIcon guifg=#6173d1 guibg=NONE gui=NONE guisp=NONE |
highlight NvimTreeFolderName guifg=#6173d1 guibg=NONE gui=NONE guisp=NONE |
highlight NvimTreeGitDeleted guifg=#b6776b guibg=NONE gui=NONE guisp=NONE |
highlight NvimTreeGitDirty guifg=#d9c679 guibg=NONE gui=NONE guisp=NONE |
highlight NvimTreeGitMerge guifg=#d88e78 guibg=NONE gui=NONE guisp=NONE |
highlight NvimTreeGitNew guifg=#4ca585 guibg=NONE gui=NONE guisp=NONE |
highlight NvimTreeImageFile guifg=#bcbbb3 guibg=NONE gui=NONE guisp=NONE |
highlight NvimTreeIndentMarker guifg=#39506d guibg=NONE gui=NONE guisp=NONE |
highlight NvimTreeNormal guifg=#A6A6A2 guibg=#192330 gui=NONE guisp=NONE |
highlight NvimTreeOpenedFile guifg=#719fa9 guibg=NONE gui=NONE guisp=NONE |
highlight NvimTreeOpenedFolderName guifg=#7988d8 guibg=NONE gui=NONE guisp=NONE |
highlight NvimTreeRootFolder guifg=#d88e78 guibg=NONE gui=bold guisp=NONE |
highlight NvimTreeSpecialFile guifg=#60c1d2 guibg=NONE gui=NONE guisp=NONE |
highlight NvimTreeSymlink guifg=#4b7983 guibg=NONE gui=NONE guisp=NONE |
highlight Operator guifg=#B9B9B5 guibg=NONE gui=NONE guisp=NONE |
highlight Pmenu guifg=#A6A6A2 guibg=#2b3b51 gui=NONE guisp=NONE |
highlight PmenuSel guifg=NONE guibg=#58658A gui=NONE guisp=NONE |
highlight PmenuThumb guifg=NONE guibg=#58658A gui=NONE guisp=NONE |
highlight PounceAccept guifg=#1d2a39 guibg=#de9f8c gui=NONE guisp=NONE |
highlight PounceAcceptBest guifg=#1d2a39 guibg=#78cad9 gui=NONE guisp=NONE |
highlight PounceGap guifg=#A6A6A2 guibg=#2b3b51 gui=NONE guisp=NONE |
highlight PounceMatch guifg=#A6A6A2 guibg=#58658A gui=NONE guisp=NONE |
highlight PreProc guifg=#d5b192 guibg=NONE gui=NONE guisp=NONE |
highlight Search guifg=#A6A6A2 guibg=#58658A gui=NONE guisp=NONE |
highlight SignColumn guifg=#71839b guibg=NONE gui=NONE guisp=NONE |
highlight Sneak guifg=#192330 guibg=#cea37f gui=NONE guisp=NONE |
highlight SneakScope guifg=NONE guibg=#2b3b51 gui=NONE guisp=NONE |
highlight Special guifg=#4ca585 guibg=NONE gui=NONE guisp=NONE |
highlight SpellBad guifg=NONE guibg=NONE gui=undercurl guisp=#b6776b |
highlight SpellCap guifg=NONE guibg=NONE gui=undercurl guisp=#d9c679 |
highlight SpellLocal guifg=NONE guibg=NONE gui=undercurl guisp=#6173d1 |
highlight SpellRare guifg=NONE guibg=NONE gui=undercurl guisp=#6173d1 |
highlight Statement guifg=#cea37f guibg=NONE gui=NONE guisp=NONE |
highlight StatusLine guifg=#B9B9B5 guibg=#192330 gui=NONE guisp=NONE |
highlight StatusLineNC guifg=#71839b guibg=#192330 gui=NONE guisp=NONE |
highlight String guifg=#60c1d2 guibg=NONE gui=NONE guisp=NONE |
highlight Substitute guifg=#1d2a39 guibg=#b6776b gui=NONE guisp=NONE |
highlight TSConstBuiltin guifg=#5262b2 guibg=NONE gui=NONE guisp=NONE |
highlight TSConstructor guifg=#cea37f guibg=NONE gui=NONE guisp=NONE |
highlight TSDanger guifg=#b6776b guibg=NONE gui=NONE guisp=NONE |
highlight TSError guifg=#b6776b guibg=NONE gui=NONE guisp=NONE |
highlight TSField guifg=#af8b6c guibg=NONE gui=NONE guisp=NONE |
highlight TSFuncBuiltin guifg=#b8a867 guibg=NONE gui=NONE guisp=NONE |
highlight TSFuncMacro guifg=#b8a867 guibg=NONE gui=NONE guisp=NONE |
highlight TSKeywordFunction guifg=#b8a867 guibg=NONE gui=NONE guisp=NONE |
highlight TSKeywordOperator guifg=#B9B9B5 guibg=NONE gui=bold guisp=NONE |
highlight TSNamespace guifg=#9b655b guibg=NONE gui=NONE guisp=NONE |
highlight TSNote guifg=#6173d1 guibg=NONE gui=NONE guisp=NONE |
highlight TSOperator guifg=#B9B9B5 guibg=NONE gui=NONE guisp=NONE |
highlight TSPunctBracket guifg=#B9B9B5 guibg=NONE gui=NONE guisp=NONE |
highlight TSPunctDelimiter guifg=#B9B9B5 guibg=NONE gui=NONE guisp=NONE |
highlight TSPunctSpecial guifg=#B9B9B5 guibg=NONE gui=NONE guisp=NONE |
highlight TSStringEscape guifg=#7988d8 guibg=NONE gui=bold guisp=NONE |
highlight TSStringRegex guifg=#7988d8 guibg=NONE gui=NONE guisp=NONE |
highlight TSTextReference guifg=#cea37f guibg=NONE gui=NONE guisp=NONE |
highlight TSTypeBuiltin guifg=#9b655b guibg=NONE gui=NONE guisp=NONE |
highlight TSURI guifg=#60c1d2 guibg=NONE gui=bold guisp=NONE |
highlight TSVariable guifg=#dfcf8d guibg=NONE gui=NONE guisp=NONE |
highlight TSVariableBuiltin guifg=#b8a867 guibg=NONE gui=NONE guisp=NONE |
highlight TSWarning guifg=#d9c679 guibg=NONE gui=NONE guisp=NONE |
highlight TabLine guifg=#71839b guibg=#212e3f gui=NONE guisp=NONE |
highlight TabLineFill guifg=NONE guibg=#192330 gui=NONE guisp=NONE |
highlight TabLineSel guifg=#B9B9B5 guibg=#39506d gui=NONE guisp=NONE |
highlight TelescopeBorder guifg=#39506d guibg=NONE gui=NONE guisp=NONE |
highlight TelescopeSelectionCaret guifg=#4ca585 guibg=NONE gui=NONE guisp=NONE |
highlight Title guifg=#4ca585 guibg=NONE gui=NONE guisp=NONE |
highlight Todo guifg=#1d2a39 guibg=#6173d1 gui=NONE guisp=NONE |
highlight Type guifg=#b6776b guibg=NONE gui=NONE guisp=NONE |
highlight Underlined guifg=NONE guibg=NONE gui=underline guisp=NONE |
highlight VertSplit guifg=#39506d guibg=NONE gui=NONE guisp=NONE |
highlight Visual guifg=NONE guibg=#2b3b51 gui=NONE guisp=NONE |
highlight WarningMsg guifg=#d9c679 guibg=NONE gui=NONE guisp=NONE |
highlight WhichKeyFloat guifg=NONE guibg=#192330 gui=NONE guisp=NONE |
highlight Whitespace guifg=#29394f guibg=NONE gui=NONE guisp=NONE |
highlight WinBar guifg=#71839b guibg=#1d2a39 gui=bold guisp=NONE |
highlight WinBarNC guifg=#71839b guibg=#1d2a39 gui=bold guisp=NONE |
highlight diffAdded guifg=#4ca585 guibg=NONE gui=NONE guisp=NONE |
highlight diffChanged guifg=#d9c679 guibg=NONE gui=NONE guisp=NONE |
highlight diffFile guifg=#6173d1 guibg=NONE gui=NONE guisp=NONE |
highlight diffIndexLine guifg=#d5b192 guibg=NONE gui=NONE guisp=NONE |
highlight diffLine guifg=#5262b2 guibg=NONE gui=NONE guisp=NONE |
highlight diffNewFile guifg=#4ca585 guibg=NONE gui=NONE guisp=NONE |
highlight diffOldFile guifg=#d9c679 guibg=NONE gui=NONE guisp=NONE |
highlight diffRemoved guifg=#b6776b guibg=NONE gui=NONE guisp=NONE |
highlight rainbowcol1 guifg=#b6776b guibg=NONE gui=NONE guisp=NONE |
highlight rainbowcol2 guifg=#d9c679 guibg=NONE gui=NONE guisp=NONE |
highlight rainbowcol3 guifg=#4ca585 guibg=NONE gui=NONE guisp=NONE |
highlight rainbowcol4 guifg=#6173d1 guibg=NONE gui=NONE guisp=NONE |
highlight rainbowcol5 guifg=#60c1d2 guibg=NONE gui=NONE guisp=NONE |
highlight rainbowcol6 guifg=#cea37f guibg=NONE gui=NONE guisp=NONE |
highlight rainbowcol7 guifg=#588e9a guibg=NONE gui=NONE guisp=NONE |
highlight rustTSField guifg=#B9B9B5 guibg=NONE gui=NONE guisp=NONE |
highlight! link AerialLine Search |
highlight! link Boolean Number |
highlight! link Character String |
highlight! link CmpItemKindClass Type |
highlight! link CmpItemKindConstant TSConstant |
highlight! link CmpItemKindConstructor Function |
highlight! link CmpItemKindEnum Constant |
highlight! link CmpItemKindEnumMember TSField |
highlight! link CmpItemKindEvent Constant |
highlight! link CmpItemKindField TSField |
highlight! link CmpItemKindFunction Function |
highlight! link CmpItemKindInterface Constant |
highlight! link CmpItemKindKeyword Identifier |
highlight! link CmpItemKindMethod Function |
highlight! link CmpItemKindModule TSNamespace |
highlight! link CmpItemKindOperator Operator |
highlight! link CmpItemKindProperty TSProperty |
highlight! link CmpItemKindReference Keyword |
highlight! link CmpItemKindStruct Type |
highlight! link CmpItemKindTypeParameter TSField |
highlight! link CmpItemKindUnit Constant |
highlight! link CmpItemKindValue Keyword |
highlight! link CmpItemKindVariable TSVariable |
highlight! link CmpItemMenu Comment |
highlight! link CurSearch IncSearch |
highlight! link CursorColumn CursorLine |
highlight! link CursorIM Cursor |
highlight! link DapUIBreakpointsLine DapUILineNumber |
highlight! link DapUIFloatBorder FloatBorder |
highlight! link DapUIFrameName Normal |
highlight! link DapUILineNumber Number |
highlight! link DapUISource Keyword |
highlight! link DapUIThread String |
highlight! link DapUIType Type |
highlight! link DashboardCenter String |
highlight! link DashboardHeader Title |
highlight! link DashboardShortCut Identifier |
highlight! link Debug Special |
highlight! link Define PreProc |
highlight! link Delimiter Special |
highlight! link DiagnosticSignError DiagnosticError |
highlight! link DiagnosticSignHint DiagnosticHint |
highlight! link DiagnosticSignInfo DiagnosticInfo |
highlight! link DiagnosticSignWarn DiagnosticWarn |
highlight! link Exception Keyword |
highlight! link FidgetTask LineNr |
highlight! link FidgetTitle Title |
highlight! link Float Number |
highlight! link FocusedSymbol Search |
highlight! link Include PreProc |
highlight! link Label Conditional |
highlight! link LspSagaBorderTitle Title |
highlight! link LspSagaCodeActionContent String |
highlight! link LspSagaCodeActionTitle Title |
highlight! link Macro PreProc |
highlight! link NeoTreeDimText Conceal |
highlight! link NeoTreeNormalNC NeoTreeNormal |
highlight! link NotifyDEBUGIcon NotifyDEBUGTitle |
highlight! link NotifyERRORIcon NotifyERRORTitle |
highlight! link NotifyINFOIcon NotifyINFOTitle |
highlight! link NotifyTRACEIcon NotifyTRACETitle |
highlight! link NotifyWARNIcon NotifyWARNTitle |
highlight! link NvimTreeGitRenamed NvimTreeGitDeleted |
highlight! link NvimTreeGitStaged NvimTreeGitStaged |
highlight! link NvimTreeVertSplit VertSplit |
highlight! link PmenuSbar Pmenu |
highlight! link PreCondit PreProc |
highlight! link Question MoreMsg |
highlight! link QuickFixLine CursorLine |
highlight! link Repeat Conditional |
highlight! link SignColumnSB SignColumn |
highlight! link SpecialChar Special |
highlight! link SpecialComment Special |
highlight! link SpecialKey NonText |
highlight! link StorageClass Type |
highlight! link Structure Type |
highlight! link SymbolOutlineConnector Conceal |
highlight! link TSAttribute Constant |
highlight! link TSProperty TSField |
highlight! link Tag Special |
highlight! link TelescopeMatching Search |
highlight! link TelescopeSelection CursorLine |
highlight! link Typedef Type |
highlight! link VisualNOS visual |
highlight! link WhichKey Identifier |
highlight! link WhichKeyDesc Keyword |
highlight! link WhichKeyGroup Function |
highlight! link WhichKeySeparator Comment |
highlight! link WhichKeySeperator Comment |
highlight! link WhichKeyValue Comment |
highlight! link WildMenu Pmenu |
highlight! link illuminatedCurWord LspReferenceText |
highlight! link illuminatedWord LspReferenceText |
highlight! link lCursor Cursor |
highlight! link qfFileName Directory |
highlight! link qfLineNr lineNr
]])

local function set_terminal()
   -- stylua: ignore
  local colors = {
    "#2b2d35", "#b6776b", "#4ca585", "#d9c679", "#6173d1", "#cea37f", "#60c1d2", "#dddcd3", "#4b4c53", "#c18b81", "#67b397", "#dfcf8d", "#7988d8", "#d5b192", "#78cad9", "#e2e1da",
  }
  for i, c in ipairs(colors) do
    local n = "terminal_color_" .. i - 1
    vim.g[n] = c
  end
  if vim.fn.has("nvim") == 0 then
    vim.g.terminal_ansi_colors = vim.list(colors)
  end
end

set_terminal()
