[metadata]
name = "carbonfox"
author = "EdenEast"
origin_url = "https://github.com/EdenEast/nightfox.nvim"

[colors]
foreground = "#f2f4f8"
background = "#161616"
cursor_bg = "#f2f4f8"
cursor_border = "#f2f4f8"
cursor_fg = "#161616"
compose_cursor = '#3ddbd9'
selection_bg = "#2a2a2a"
selection_fg = "#f2f4f8"
scrollbar_thumb = "#737476"
split = "#0b0b0b"
visual_bell = "#f2f4f8"
ansi = ["#282828", "#ee5396", "#25be6a", "#08bdba", "#78a9ff", "#be95ff", "#33b1ff", "#dfdfe0"]
brights = ["#444444", "#f471a5", "#58c881", "#52c7c4", "#8cb6ff", "#c7a5ff", "#5ebeff", "#e4e4e5"]

[colors.indexed]
16 = "#ff7eb6"
17 = "#3ddbd9"

[colors.tab_bar]
background = "#0b0b0b"
inactive_tab_edge = "#0b0b0b"
inactive_tab_edge_hover = "#252525"

[colors.tab_bar.active_tab]
bg_color = "#737476"
fg_color = "#161616"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#252525"
fg_color = "#b1b2b5"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#333333"
fg_color = "#f2f4f8"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#161616"
fg_color = "#b1b2b5"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#333333"
fg_color = "#f2f4f8"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

