# Nightfox Alacritty Colors
## name: dayfox
## upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/dayfox/alacritty.toml

[colors.primary]
background = "#f6f2ee"
foreground = "#3d2b5a"
dim_foreground = "#302b5d"
bright_foreground = "#643f61"

[colors.cursor]
text = "#3d2b5a"
cursor = "#643f61"

[colors.vi_mode_cursor]
text = "#3d2b5a"
cursor = "#287980"

[colors.search.matches]
foreground = "#3d2b5a"
background = "#a4c1c2"

[colors.search.focused_match]
foreground = "#3d2b5a"
background = "#396847"

[colors.footer_bar]
foreground = "#3d2b5a"
background = "#d3c7bb"

[colors.hints.start]
foreground = "#3d2b5a"
background = "#955f61"

[colors.hints.end]
foreground = "#3d2b5a"
background = "#d3c7bb"

[colors.selection]
text = "#3d2b5a"
background = "#e7d2be"

[colors.normal]
black = "#352c24"
red = "#a5222f"
green = "#396847"
yellow = "#ac5402"
blue = "#2848a9"
magenta = "#6e33ce"
cyan = "#287980"
white = "#f2e9e1"

[colors.bright]
black = "#504740"
red = "#b64a4c"
green = "#567d60"
yellow = "#ba6e3b"
blue = "#4464b8"
magenta = "#8058d8"
cyan = "#4e8c92"
white = "#f4ece5"

[colors.dim]
black = "#29211b"
red = "#841924"
green = "#2c5237"
yellow = "#8a4201"
blue = "#1e3887"
magenta = "#5727a6"
cyan = "#1e6066"
white = "#c3bcb5"

[[colors.indexed_colors]]
index = 16
color = "#955f61"

[[colors.indexed_colors]]
index = 17
color = "#a440b5"
