local M = {}

local metas = {
  dawnfox = "light",
  dayfox = "light",
  duskfox = "dark",
  nightfox = "dark",
  nordfox = "dark",
}

local highlights = {
  dawnfox = {
    Bold = { style = "bold" },
    BufferCurrent = { bg = "#a8a3b3", fg = "#575279" },
    BufferCurrentIndex = { bg = "#a8a3b3", fg = "#286983" },
    BufferCurrentMod = { bg = "#a8a3b3", fg = "#ea9d34" },
    BufferCurrentSign = { bg = "#a8a3b3", fg = "#286983" },
    BufferCurrentTarget = { bg = "#a8a3b3", fg = "#b4637a" },
    BufferInactive = { bg = "#EBE5DF", fg = "#9893a5" },
    BufferInactiveIndex = { bg = "#EBE5DF", fg = "#9893a5" },
    BufferInactiveMod = { bg = "#EBE5DF", fg = "#f5dab6" },
    BufferInactiveSign = { bg = "#EBE5DF", fg = "#EBDFE4" },
    BufferInactiveTarget = { bg = "#EBE5DF", fg = "#b4637a" },
    BufferTabpage = { bg = "#EBE5DF", fg = "#EBDFE4" },
    BufferTabpages = { bg = "#EBE5DF" },
    BufferVisible = { bg = "#EBE5DF", fg = "#575279" },
    BufferVisibleIndex = { bg = "#EBE5DF", fg = "#286983" },
    BufferVisibleMod = { bg = "#EBE5DF", fg = "#ea9d34" },
    BufferVisibleSign = { bg = "#EBE5DF", fg = "#286983" },
    BufferVisibleTarget = { bg = "#EBE5DF", fg = "#b4637a" },
    CmpDocumentation = { bg = "#EBE5DF", fg = "#575279" },
    CmpDocumentationBorder = { bg = "#EBE5DF", fg = "#d0d8d8" },
    CmpItemAbbr = { fg = "#575279" },
    CmpItemAbbrDeprecated = { fg = "#a8a3b3", style = "strikethrough" },
    CmpItemAbbrMatch = { fg = "#295e73" },
    CmpItemAbbrMatchFuzzy = { fg = "#295e73" },
    CmpItemKindDefault = { fg = "#625C87" },
    CmpItemKindSnippet = { fg = "#625C87" },
    ColorColumn = { bg = "#EBE0DF" },
    Comment = { fg = "#9893a5", style = "NONE" },
    Conceal = { fg = "#BDBFC9" },
    Conditional = { fg = "#816b9a" },
    Constant = { fg = "#ca6e69" },
    Cursor = { bg = "#575279", fg = "#faf4ed" },
    CursorColumn = { bg = "#EBDFE4" },
    CursorLineNr = { fg = "#ea9d34", style = "bold" },
    DashboardFooter = { fg = "#ca6e69", style = "italic" },
    DiagnosticError = { fg = "#b4637a" },
    DiagnosticHint = { fg = "#618774" },
    DiagnosticInfo = { fg = "#286983" },
    DiagnosticUnderlineError = { sp = "#b4637a", style = "undercurl" },
    DiagnosticUnderlineHint = { sp = "#618774", style = "undercurl" },
    DiagnosticUnderlineInfo = { sp = "#286983", style = "undercurl" },
    DiagnosticUnderlineWarn = { sp = "#ea9d34", style = "undercurl" },
    DiagnosticVirtualTextError = { bg = "#e5c9cb", fg = "#b4637a" },
    DiagnosticVirtualTextHint = { bg = "#ccd3c9", fg = "#618774" },
    DiagnosticVirtualTextInfo = { bg = "#bbcacd", fg = "#286983" },
    DiagnosticVirtualTextWarn = { bg = "#f5dab6", fg = "#ea9d34" },
    DiagnosticWarn = { fg = "#ea9d34" },
    DiffAdd = { bg = "#dbded5" },
    DiffChange = { bg = "#d0d8d8" },
    DiffDelete = { bg = "#ecd7d6" },
    DiffText = { bg = "#a6bcc3" },
    Directory = { fg = "#295e73" },
    EndOfBuffer = { fg = "#faf4ed" },
    Error = { fg = "#b4637a" },
    ErrorMsg = { fg = "#b4637a" },
    FernBranchText = { fg = "#286983" },
    FloatBorder = { fg = "#a8a3b3" },
    FoldColumn = { fg = "#EBDFE4" },
    Folded = { bg = "#EBDFE4", fg = "#a8a3b3" },
    Function = { fg = "#295e73", style = "NONE" },
    GitGutterAdd = { fg = "#618774" },
    GitGutterChange = { fg = "#ea9d34" },
    GitGutterDelete = { fg = "#b4637a" },
    GitSignsAdd = { fg = "#618774" },
    GitSignsChange = { fg = "#b4637a" },
    GitSignsDelete = { fg = "#ea9d34" },
    GlyphPallet0 = { fg = "#575279" },
    GlyphPallet1 = { fg = "#b4637a" },
    GlyphPallet10 = { fg = "#629f81" },
    GlyphPallet11 = { fg = "#eea846" },
    GlyphPallet12 = { fg = "#2d81a3" },
    GlyphPallet13 = { fg = "#9a80b9" },
    GlyphPallet14 = { fg = "#5ca7b4" },
    GlyphPallet15 = { fg = "#e6ebf3" },
    GlyphPallet2 = { fg = "#618774" },
    GlyphPallet3 = { fg = "#ea9d34" },
    GlyphPallet4 = { fg = "#286983" },
    GlyphPallet5 = { fg = "#907aa9" },
    GlyphPallet6 = { fg = "#56949f" },
    GlyphPallet7 = { fg = "#e6ebf3" },
    GlyphPallet8 = { fg = "#5f5695" },
    GlyphPallet9 = { fg = "#c26d85" },
    HopNextKey = { fg = "#56949f", style = "bold" },
    HopNextKey1 = { fg = "#286983", style = "bold" },
    HopNextKey2 = { fg = "#2d81a3" },
    HopUnmatched = { fg = "#9893a5" },
    Identifier = { fg = "#56949f", style = "NONE" },
    IncSearch = { bg = "#618774", fg = "#b8cece" },
    Italic = { style = "italic" },
    Keyword = { fg = "#907aa9", style = "NONE" },
    LightspeedGreyWash = { fg = "#9893a5" },
    LineNr = { fg = "#a8a3b3" },
    LspCodeLens = { fg = "#9893a5" },
    LspCodeLensSeparator = { fg = "#a8a3b3" },
    LspFloatWinBorder = { fg = "#a8a3b3" },
    LspFloatWinNormal = { bg = "#EBE5DF" },
    LspReferenceRead = { bg = "#d0d8d8" },
    LspReferenceText = { bg = "#d0d8d8" },
    LspReferenceWrite = { bg = "#d0d8d8" },
    LspSagaCodeActionBorder = { fg = "#a8a3b3" },
    LspSagaDefPreviewBorder = { fg = "#a8a3b3" },
    LspSagaFinderSelection = { fg = "#d0d8d8" },
    LspSagaHoverBorder = { fg = "#a8a3b3" },
    LspSagaRenameBorder = { fg = "#a8a3b3" },
    LspSagaSignatureHelpBorder = { fg = "#b4637a" },
    LspSignatureActiveParameter = { fg = "#b8cece" },
    LspTroubleCount = { bg = "#a8a3b3", fg = "#907aa9" },
    LspTroubleNormal = { bg = "#EBE5DF", fg = "#a8a3b3" },
    LspTroubleText = { fg = "#625C87" },
    MatchParen = { fg = "#ea9d34", style = "bold" },
    ModeMsg = { fg = "#ea9d34", style = "bold" },
    MoreMsg = { fg = "#286983", style = "bold" },
    MsgArea = { fg = "#625C87" },
    NeogitBranch = { fg = "#ea9d34" },
    NeogitDiffAdd = { fg = "#618774" },
    NeogitDiffAddHighlight = { bg = "#dbded5" },
    NeogitDiffContextHighlight = { bg = "#d0d8d8" },
    NeogitDiffDelete = { fg = "#b4637a" },
    NeogitDiffDeleteHighlight = { bg = "#ecd7d6" },
    NeogitHunkHeader = { bg = "#EBDFE4", fg = "#286983" },
    NeogitHunkHeaderHighlight = { bg = "#d0d8d8", fg = "#286983" },
    NeogitNotificationError = { fg = "#b4637a" },
    NeogitNotificationInfo = { fg = "#286983" },
    NeogitNotificationWarning = { fg = "#ea9d34" },
    NeogitRemote = { fg = "#618774" },
    NonText = { fg = "#BDBFC9" },
    Normal = { bg = "#faf4ed", fg = "#575279" },
    NormalFloat = { bg = "#EBE5DF", fg = "#575279" },
    NormalNC = { bg = "#faf4ed", fg = "#575279" },
    Number = { fg = "#d7827e", style = "NONE" },
    NvimTreeEmptyFolderName = { fg = "#a8a3b3" },
    NvimTreeFolderIcon = { fg = "#286983" },
    NvimTreeFolderName = { fg = "#286983" },
    NvimTreeGitDeleted = { fg = "#b4637a" },
    NvimTreeGitDirty = { fg = "#ea9d34" },
    NvimTreeGitNew = { fg = "#618774" },
    NvimTreeImageFile = { fg = "#e6ebf3" },
    NvimTreeIndentMarker = { fg = "#BDBFC9" },
    NvimTreeNormal = { bg = "#EBE5DF", fg = "#575279" },
    NvimTreeOpenedFile = { fg = "#c9709e" },
    NvimTreeOpenedFolderName = { fg = "#295e73" },
    NvimTreeRootFolder = { fg = "#d7827e", style = "bold" },
    NvimTreeSpecialFile = { fg = "#56949f" },
    NvimTreeSymlink = { fg = "#de8db7" },
    Operator = { fg = "#625C87" },
    Pmenu = { bg = "#d0d8d8", fg = "#575279" },
    PmenuSel = { bg = "#b8cece" },
    PmenuThumb = { bg = "#b8cece" },
    PreProc = { fg = "#c9709e" },
    Search = { bg = "#b8cece", fg = "#575279" },
    SignColumn = { fg = "#a8a3b3" },
    Sneak = { bg = "#907aa9", fg = "#EBE5DF" },
    SneakScope = { bg = "#d0d8d8" },
    Special = { fg = "#295e73" },
    SpellBad = { sp = "#b4637a", style = "undercurl" },
    SpellCap = { sp = "#ea9d34", style = "undercurl" },
    SpellLocal = { sp = "#286983", style = "undercurl" },
    SpellRare = { sp = "#286983", style = "undercurl" },
    Statement = { fg = "#907aa9", style = "NONE" },
    StatusLine = { bg = "#EBE5DF", fg = "#625C87" },
    StatusLineNC = { bg = "#EBE5DF", fg = "#a8a3b3" },
    String = { fg = "#618774", style = "NONE" },
    Substitute = { bg = "#b4637a", fg = "#faf4ed" },
    TSConstBuiltin = { fg = "#ca6e69" },
    TSConstructor = { fg = "#907aa9" },
    TSDanger = { fg = "#b4637a" },
    TSError = { fg = "#b4637a" },
    TSField = { fg = "#286983" },
    TSFuncBuiltin = { fg = "#b4637a" },
    TSFuncMacro = { fg = "#b4637a" },
    TSKeywordFunction = { fg = "#b4637a", style = "NONE" },
    TSKeywordOperator = { fg = "#625C87", style = "bold" },
    TSNamespace = { fg = "#50848c" },
    TSNote = { fg = "#286983" },
    TSOperator = { fg = "#625C87" },
    TSPunctBracket = { fg = "#625C87" },
    TSPunctDelimiter = { fg = "#625C87" },
    TSPunctSpecial = { fg = "#625C87" },
    TSStringEscape = { fg = "#dd9024", style = "bold" },
    TSStringRegex = { fg = "#dd9024", style = "NONE" },
    TSTextReference = { fg = "#907aa9" },
    TSTypeBuiltin = { fg = "#50848c", style = "NONE" },
    TSURI = { fg = "#56949f", style = "bold" },
    TSVariable = { fg = "#575279", style = "NONE" },
    TSVariableBuiltin = { fg = "#b4637a", style = "NONE" },
    TSWarning = { fg = "#ea9d34" },
    TabLine = { bg = "#EBE0DF", fg = "#a8a3b3" },
    TabLineFill = { bg = "#EBE5DF" },
    TabLineSel = { bg = "#BDBFC9", fg = "#625C87" },
    TelescopeBorder = { fg = "#BDBFC9" },
    TelescopeMatching = { bg = "#b8cece", fg = "#575279" },
    TelescopeSelection = { bg = "#d0d8d8" },
    TelescopeSelectionCaret = { fg = "#618774" },
    Title = { fg = "#295e73" },
    Todo = { bg = "#286983", fg = "#faf4ed" },
    Type = { fg = "#ea9d34", style = "NONE" },
    Underlined = { style = "underline" },
    VertSplit = { fg = "#BDBFC9" },
    Visual = { bg = "#d0d8d8" },
    WarningMsg = { fg = "#ea9d34" },
    WhichKeyFloat = { bg = "#EBE5DF" },
    Whitespace = { fg = "#EBE0DF" },
    diffAdded = { fg = "#618774" },
    diffChanged = { fg = "#ea9d34" },
    diffFile = { fg = "#286983" },
    diffIndexLine = { fg = "#c9709e" },
    diffLine = { fg = "#ca6e69" },
    diffNewFile = { fg = "#618774" },
    diffOldFile = { fg = "#ea9d34" },
    diffRemoved = { fg = "#b4637a" },
    rainboecol1 = { fg = "#b4637a" },
    rainboecol2 = { fg = "#ea9d34" },
    rainboecol3 = { fg = "#618774" },
    rainboecol4 = { fg = "#286983" },
    rainboecol5 = { fg = "#56949f" },
    rainboecol6 = { fg = "#907aa9" },
    rainboecol7 = { fg = "#d685af" },
    rustTSField = { fg = "#625C87" },
  },
  dayfox = {
    Bold = { style = "bold" },
    BufferCurrent = { bg = "#2E537D", fg = "#1d344f" },
    BufferCurrentIndex = { bg = "#2E537D", fg = "#4d688e" },
    BufferCurrentMod = { bg = "#2E537D", fg = "#ba793e" },
    BufferCurrentSign = { bg = "#2E537D", fg = "#4d688e" },
    BufferCurrentTarget = { bg = "#2E537D", fg = "#b95d76" },
    BufferInactive = { bg = "#dbdbdb", fg = "#7f848e" },
    BufferInactiveIndex = { bg = "#dbdbdb", fg = "#7f848e" },
    BufferInactiveMod = { bg = "#dbdbdb", fg = "#dcc8b6" },
    BufferInactiveSign = { bg = "#dbdbdb", fg = "#CED6DB" },
    BufferInactiveTarget = { bg = "#dbdbdb", fg = "#b95d76" },
    BufferTabpage = { bg = "#dbdbdb", fg = "#CED6DB" },
    BufferTabpages = { bg = "#dbdbdb" },
    BufferVisible = { bg = "#dbdbdb", fg = "#1d344f" },
    BufferVisibleIndex = { bg = "#dbdbdb", fg = "#4d688e" },
    BufferVisibleMod = { bg = "#dbdbdb", fg = "#ba793e" },
    BufferVisibleSign = { bg = "#dbdbdb", fg = "#4d688e" },
    BufferVisibleTarget = { bg = "#dbdbdb", fg = "#b95d76" },
    CmpDocumentation = { bg = "#dbdbdb", fg = "#1d344f" },
    CmpDocumentationBorder = { bg = "#dbdbdb", fg = "#ced5de" },
    CmpItemAbbr = { fg = "#1d344f" },
    CmpItemAbbrDeprecated = { fg = "#2E537D", style = "strikethrough" },
    CmpItemAbbrMatch = { fg = "#485e7d" },
    CmpItemAbbrMatchFuzzy = { fg = "#485e7d" },
    CmpItemKindDefault = { fg = "#233f5e" },
    CmpItemKindSnippet = { fg = "#233f5e" },
    ColorColumn = { bg = "#DBCECE" },
    Comment = { fg = "#7f848e", style = "NONE" },
    Conceal = { fg = "#bebebe" },
    Conditional = { fg = "#806589" },
    Constant = { fg = "#d76558" },
    Cursor = { bg = "#1d344f", fg = "#eaeaea" },
    CursorColumn = { bg = "#CED6DB" },
    CursorLineNr = { fg = "#ba793e", style = "bold" },
    DashboardFooter = { fg = "#d76558", style = "italic" },
    DiagnosticError = { fg = "#b95d76" },
    DiagnosticHint = { fg = "#618774" },
    DiagnosticInfo = { fg = "#4d688e" },
    DiagnosticUnderlineError = { sp = "#b95d76", style = "undercurl" },
    DiagnosticUnderlineHint = { sp = "#618774", style = "undercurl" },
    DiagnosticUnderlineInfo = { sp = "#4d688e", style = "undercurl" },
    DiagnosticUnderlineWarn = { sp = "#ba793e", style = "undercurl" },
    DiagnosticVirtualTextError = { bg = "#dbc0c7", fg = "#b95d76" },
    DiagnosticVirtualTextHint = { bg = "#c1ccc7", fg = "#618774" },
    DiagnosticVirtualTextInfo = { bg = "#bbc3ce", fg = "#4d688e" },
    DiagnosticVirtualTextWarn = { bg = "#dcc8b6", fg = "#ba793e" },
    DiagnosticWarn = { fg = "#ba793e" },
    DiffAdd = { bg = "#cfd6d2" },
    DiffChange = { bg = "#cbd0d8" },
    DiffDelete = { bg = "#e0ced3" },
    DiffText = { bg = "#abb6c5" },
    Directory = { fg = "#485e7d" },
    EndOfBuffer = { fg = "#eaeaea" },
    Error = { fg = "#b95d76" },
    ErrorMsg = { fg = "#b95d76" },
    FernBranchText = { fg = "#4d688e" },
    FloatBorder = { fg = "#2E537D" },
    FoldColumn = { fg = "#CED6DB" },
    Folded = { bg = "#CED6DB", fg = "#2E537D" },
    Function = { fg = "#485e7d", style = "NONE" },
    GitGutterAdd = { fg = "#618774" },
    GitGutterChange = { fg = "#ba793e" },
    GitGutterDelete = { fg = "#b95d76" },
    GitSignsAdd = { fg = "#618774" },
    GitSignsChange = { fg = "#b95d76" },
    GitSignsDelete = { fg = "#ba793e" },
    GlyphPallet0 = { fg = "#1d344f" },
    GlyphPallet1 = { fg = "#b95d76" },
    GlyphPallet10 = { fg = "#629f81" },
    GlyphPallet11 = { fg = "#ca884a" },
    GlyphPallet12 = { fg = "#4e75aa" },
    GlyphPallet13 = { fg = "#9f75ac" },
    GlyphPallet14 = { fg = "#74b2c9" },
    GlyphPallet15 = { fg = "#cfd6dd" },
    GlyphPallet2 = { fg = "#618774" },
    GlyphPallet3 = { fg = "#ba793e" },
    GlyphPallet4 = { fg = "#4d688e" },
    GlyphPallet5 = { fg = "#8e6f98" },
    GlyphPallet6 = { fg = "#6ca7bd" },
    GlyphPallet7 = { fg = "#cfd6dd" },
    GlyphPallet8 = { fg = "#24476f" },
    GlyphPallet9 = { fg = "#c76882" },
    HopNextKey = { fg = "#6ca7bd", style = "bold" },
    HopNextKey1 = { fg = "#4d688e", style = "bold" },
    HopNextKey2 = { fg = "#4e75aa" },
    HopUnmatched = { fg = "#7f848e" },
    Identifier = { fg = "#6ca7bd", style = "NONE" },
    IncSearch = { bg = "#618774", fg = "#b6c4d9" },
    Italic = { style = "italic" },
    Keyword = { fg = "#8e6f98", style = "NONE" },
    LightspeedGreyWash = { fg = "#7f848e" },
    LineNr = { fg = "#2E537D" },
    LspCodeLens = { fg = "#7f848e" },
    LspCodeLensSeparator = { fg = "#2E537D" },
    LspFloatWinBorder = { fg = "#2E537D" },
    LspFloatWinNormal = { bg = "#dbdbdb" },
    LspReferenceRead = { bg = "#ced5de" },
    LspReferenceText = { bg = "#ced5de" },
    LspReferenceWrite = { bg = "#ced5de" },
    LspSagaCodeActionBorder = { fg = "#2E537D" },
    LspSagaDefPreviewBorder = { fg = "#2E537D" },
    LspSagaFinderSelection = { fg = "#ced5de" },
    LspSagaHoverBorder = { fg = "#2E537D" },
    LspSagaRenameBorder = { fg = "#2E537D" },
    LspSagaSignatureHelpBorder = { fg = "#b95d76" },
    LspSignatureActiveParameter = { fg = "#b6c4d9" },
    LspTroubleCount = { bg = "#2E537D", fg = "#8e6f98" },
    LspTroubleNormal = { bg = "#dbdbdb", fg = "#2E537D" },
    LspTroubleText = { fg = "#233f5e" },
    MatchParen = { fg = "#ba793e", style = "bold" },
    ModeMsg = { fg = "#ba793e", style = "bold" },
    MoreMsg = { fg = "#4d688e", style = "bold" },
    MsgArea = { fg = "#233f5e" },
    NeogitBranch = { fg = "#ba793e" },
    NeogitDiffAdd = { fg = "#618774" },
    NeogitDiffAddHighlight = { bg = "#cfd6d2" },
    NeogitDiffContextHighlight = { bg = "#cbd0d8" },
    NeogitDiffDelete = { fg = "#b95d76" },
    NeogitDiffDeleteHighlight = { bg = "#e0ced3" },
    NeogitHunkHeader = { bg = "#CED6DB", fg = "#4d688e" },
    NeogitHunkHeaderHighlight = { bg = "#ced5de", fg = "#4d688e" },
    NeogitNotificationError = { fg = "#b95d76" },
    NeogitNotificationInfo = { fg = "#4d688e" },
    NeogitNotificationWarning = { fg = "#ba793e" },
    NeogitRemote = { fg = "#618774" },
    NonText = { fg = "#bebebe" },
    Normal = { bg = "#eaeaea", fg = "#1d344f" },
    NormalFloat = { bg = "#dbdbdb", fg = "#1d344f" },
    NormalNC = { bg = "#eaeaea", fg = "#1d344f" },
    Number = { fg = "#e3786c", style = "NONE" },
    NvimTreeEmptyFolderName = { fg = "#2E537D" },
    NvimTreeFolderIcon = { fg = "#4d688e" },
    NvimTreeFolderName = { fg = "#4d688e" },
    NvimTreeGitDeleted = { fg = "#b95d76" },
    NvimTreeGitDirty = { fg = "#ba793e" },
    NvimTreeGitNew = { fg = "#618774" },
    NvimTreeImageFile = { fg = "#cfd6dd" },
    NvimTreeIndentMarker = { fg = "#bebebe" },
    NvimTreeNormal = { bg = "#dbdbdb", fg = "#1d344f" },
    NvimTreeOpenedFile = { fg = "#c9709e" },
    NvimTreeOpenedFolderName = { fg = "#485e7d" },
    NvimTreeRootFolder = { fg = "#e3786c", style = "bold" },
    NvimTreeSpecialFile = { fg = "#6ca7bd" },
    NvimTreeSymlink = { fg = "#de8db7" },
    Operator = { fg = "#233f5e" },
    Pmenu = { bg = "#ced5de", fg = "#1d344f" },
    PmenuSel = { bg = "#b6c4d9" },
    PmenuThumb = { bg = "#b6c4d9" },
    PreProc = { fg = "#c9709e" },
    Search = { bg = "#b6c4d9", fg = "#1d344f" },
    SignColumn = { fg = "#2E537D" },
    Sneak = { bg = "#8e6f98", fg = "#dbdbdb" },
    SneakScope = { bg = "#ced5de" },
    Special = { fg = "#485e7d" },
    SpellBad = { sp = "#b95d76", style = "undercurl" },
    SpellCap = { sp = "#ba793e", style = "undercurl" },
    SpellLocal = { sp = "#4d688e", style = "undercurl" },
    SpellRare = { sp = "#4d688e", style = "undercurl" },
    Statement = { fg = "#8e6f98", style = "NONE" },
    StatusLine = { bg = "#dbdbdb", fg = "#233f5e" },
    StatusLineNC = { bg = "#dbdbdb", fg = "#2E537D" },
    String = { fg = "#618774", style = "NONE" },
    Substitute = { bg = "#b95d76", fg = "#eaeaea" },
    TSConstBuiltin = { fg = "#d76558" },
    TSConstructor = { fg = "#8e6f98" },
    TSDanger = { fg = "#b95d76" },
    TSError = { fg = "#b95d76" },
    TSField = { fg = "#4d688e" },
    TSFuncBuiltin = { fg = "#b95d76" },
    TSFuncMacro = { fg = "#b95d76" },
    TSKeywordFunction = { fg = "#b95d76", style = "NONE" },
    TSKeywordOperator = { fg = "#233f5e", style = "bold" },
    TSNamespace = { fg = "#5a99b0" },
    TSNote = { fg = "#4d688e" },
    TSOperator = { fg = "#233f5e" },
    TSPunctBracket = { fg = "#233f5e" },
    TSPunctDelimiter = { fg = "#233f5e" },
    TSPunctSpecial = { fg = "#233f5e" },
    TSStringEscape = { fg = "#a36f3e", style = "bold" },
    TSStringRegex = { fg = "#a36f3e", style = "NONE" },
    TSTextReference = { fg = "#8e6f98" },
    TSTypeBuiltin = { fg = "#5a99b0", style = "NONE" },
    TSURI = { fg = "#6ca7bd", style = "bold" },
    TSVariable = { fg = "#1d344f", style = "NONE" },
    TSVariableBuiltin = { fg = "#b95d76", style = "NONE" },
    TSWarning = { fg = "#ba793e" },
    TabLine = { bg = "#DBCECE", fg = "#2E537D" },
    TabLineFill = { bg = "#dbdbdb" },
    TabLineSel = { bg = "#bebebe", fg = "#233f5e" },
    TelescopeBorder = { fg = "#bebebe" },
    TelescopeMatching = { bg = "#b6c4d9", fg = "#1d344f" },
    TelescopeSelection = { bg = "#ced5de" },
    TelescopeSelectionCaret = { fg = "#618774" },
    Title = { fg = "#485e7d" },
    Todo = { bg = "#4d688e", fg = "#eaeaea" },
    Type = { fg = "#ba793e", style = "NONE" },
    Underlined = { style = "underline" },
    VertSplit = { fg = "#bebebe" },
    Visual = { bg = "#ced5de" },
    WarningMsg = { fg = "#ba793e" },
    WhichKeyFloat = { bg = "#dbdbdb" },
    Whitespace = { fg = "#DBCECE" },
    diffAdded = { fg = "#618774" },
    diffChanged = { fg = "#ba793e" },
    diffFile = { fg = "#4d688e" },
    diffIndexLine = { fg = "#c9709e" },
    diffLine = { fg = "#d76558" },
    diffNewFile = { fg = "#618774" },
    diffOldFile = { fg = "#ba793e" },
    diffRemoved = { fg = "#b95d76" },
    rainboecol1 = { fg = "#b95d76" },
    rainboecol2 = { fg = "#ba793e" },
    rainboecol3 = { fg = "#618774" },
    rainboecol4 = { fg = "#4d688e" },
    rainboecol5 = { fg = "#6ca7bd" },
    rainboecol6 = { fg = "#8e6f98" },
    rainboecol7 = { fg = "#d685af" },
    rustTSField = { fg = "#233f5e" },
  },
  duskfox = {
    Bold = { style = "bold" },
    BufferCurrent = { bg = "#555169", fg = "#e0def4" },
    BufferCurrentIndex = { bg = "#555169", fg = "#569fba" },
    BufferCurrentMod = { bg = "#555169", fg = "#f6c177" },
    BufferCurrentSign = { bg = "#555169", fg = "#569fba" },
    BufferCurrentTarget = { bg = "#555169", fg = "#eb6f92" },
    BufferInactive = { bg = "#191726", fg = "#817c9c" },
    BufferInactiveIndex = { bg = "#191726", fg = "#817c9c" },
    BufferInactiveMod = { bg = "#191726", fg = "#4a3a24" },
    BufferInactiveSign = { bg = "#191726", fg = "#373354" },
    BufferInactiveTarget = { bg = "#191726", fg = "#eb6f92" },
    BufferTabpage = { bg = "#191726", fg = "#373354" },
    BufferTabpages = { bg = "#191726" },
    BufferVisible = { bg = "#191726", fg = "#e0def4" },
    BufferVisibleIndex = { bg = "#191726", fg = "#569fba" },
    BufferVisibleMod = { bg = "#191726", fg = "#f6c177" },
    BufferVisibleSign = { bg = "#191726", fg = "#569fba" },
    BufferVisibleTarget = { bg = "#191726", fg = "#eb6f92" },
    CmpDocumentation = { bg = "#191726", fg = "#e0def4" },
    CmpDocumentationBorder = { bg = "#191726", fg = "#433c59" },
    CmpItemAbbr = { fg = "#e0def4" },
    CmpItemAbbrDeprecated = { fg = "#555169", style = "strikethrough" },
    CmpItemAbbrMatch = { fg = "#65b1cd" },
    CmpItemAbbrMatchFuzzy = { fg = "#65b1cd" },
    CmpItemKindDefault = { fg = "#D3D1E6" },
    CmpItemKindSnippet = { fg = "#D3D1E6" },
    ColorColumn = { bg = "#2D2A45" },
    Comment = { fg = "#817c9c", style = "NONE" },
    Conceal = { fg = "#4B4673" },
    Conditional = { fg = "#ccb1ed" },
    Constant = { fg = "#f0a4a2" },
    Cursor = { bg = "#e0def4", fg = "#232136" },
    CursorColumn = { bg = "#373354" },
    CursorLineNr = { fg = "#f6c177", style = "bold" },
    DashboardFooter = { fg = "#f0a4a2", style = "italic" },
    DiagnosticError = { fg = "#eb6f92" },
    DiagnosticHint = { fg = "#a3be8c" },
    DiagnosticInfo = { fg = "#569fba" },
    DiagnosticUnderlineError = { sp = "#eb6f92", style = "undercurl" },
    DiagnosticUnderlineHint = { sp = "#a3be8c", style = "undercurl" },
    DiagnosticUnderlineInfo = { sp = "#569fba", style = "undercurl" },
    DiagnosticUnderlineWarn = { sp = "#f6c177", style = "undercurl" },
    DiagnosticVirtualTextError = { bg = "#3b1c24", fg = "#eb6f92" },
    DiagnosticVirtualTextHint = { bg = "#31392a", fg = "#a3be8c" },
    DiagnosticVirtualTextInfo = { bg = "#1a3038", fg = "#569fba" },
    DiagnosticVirtualTextWarn = { bg = "#4a3a24", fg = "#f6c177" },
    DiagnosticWarn = { fg = "#f6c177" },
    DiffAdd = { bg = "#3d4047" },
    DiffChange = { bg = "#2d3a50" },
    DiffDelete = { bg = "#4b3148" },
    DiffText = { bg = "#37536b" },
    Directory = { fg = "#65b1cd" },
    EndOfBuffer = { fg = "#232136" },
    Error = { fg = "#eb6f92" },
    ErrorMsg = { fg = "#eb6f92" },
    FernBranchText = { fg = "#569fba" },
    FloatBorder = { fg = "#555169" },
    FoldColumn = { fg = "#373354" },
    Folded = { bg = "#373354", fg = "#555169" },
    Function = { fg = "#65b1cd", style = "NONE" },
    GitGutterAdd = { fg = "#a3be8c" },
    GitGutterChange = { fg = "#f6c177" },
    GitGutterDelete = { fg = "#eb6f92" },
    GitSignsAdd = { fg = "#a3be8c" },
    GitSignsChange = { fg = "#eb6f92" },
    GitSignsDelete = { fg = "#f6c177" },
    GlyphPallet0 = { fg = "#393552" },
    GlyphPallet1 = { fg = "#eb6f92" },
    GlyphPallet10 = { fg = "#b1d196" },
    GlyphPallet11 = { fg = "#f9cb8c" },
    GlyphPallet12 = { fg = "#65b1cd" },
    GlyphPallet13 = { fg = "#ccb1ed" },
    GlyphPallet14 = { fg = "#a6dae3" },
    GlyphPallet15 = { fg = "#e2e0f7" },
    GlyphPallet2 = { fg = "#a3be8c" },
    GlyphPallet3 = { fg = "#f6c177" },
    GlyphPallet4 = { fg = "#569fba" },
    GlyphPallet5 = { fg = "#c4a7e7" },
    GlyphPallet6 = { fg = "#9ccfd8" },
    GlyphPallet7 = { fg = "#e2e0f7" },
    GlyphPallet8 = { fg = "#47407d" },
    GlyphPallet9 = { fg = "#f083a2" },
    HopNextKey = { fg = "#9ccfd8", style = "bold" },
    HopNextKey1 = { fg = "#569fba", style = "bold" },
    HopNextKey2 = { fg = "#4a869c" },
    HopUnmatched = { fg = "#817c9c" },
    Identifier = { fg = "#9ccfd8", style = "NONE" },
    IncSearch = { bg = "#a3be8c", fg = "#2d3a50" },
    Italic = { style = "italic" },
    Keyword = { fg = "#c4a7e7", style = "NONE" },
    LightspeedGreyWash = { fg = "#817c9c" },
    LineNr = { fg = "#555169" },
    LspCodeLens = { fg = "#817c9c" },
    LspCodeLensSeparator = { fg = "#555169" },
    LspFloatWinBorder = { fg = "#555169" },
    LspFloatWinNormal = { bg = "#191726" },
    LspReferenceRead = { bg = "#433c59" },
    LspReferenceText = { bg = "#433c59" },
    LspReferenceWrite = { bg = "#433c59" },
    LspSagaCodeActionBorder = { fg = "#555169" },
    LspSagaDefPreviewBorder = { fg = "#555169" },
    LspSagaFinderSelection = { fg = "#433c59" },
    LspSagaHoverBorder = { fg = "#555169" },
    LspSagaRenameBorder = { fg = "#555169" },
    LspSagaSignatureHelpBorder = { fg = "#eb6f92" },
    LspSignatureActiveParameter = { fg = "#2d3a50" },
    LspTroubleCount = { bg = "#555169", fg = "#c4a7e7" },
    LspTroubleNormal = { bg = "#191726", fg = "#555169" },
    LspTroubleText = { fg = "#D3D1E6" },
    MatchParen = { fg = "#f6c177", style = "bold" },
    ModeMsg = { fg = "#f6c177", style = "bold" },
    MoreMsg = { fg = "#569fba", style = "bold" },
    MsgArea = { fg = "#D3D1E6" },
    NeogitBranch = { fg = "#f6c177" },
    NeogitDiffAdd = { fg = "#a3be8c" },
    NeogitDiffAddHighlight = { bg = "#3d4047" },
    NeogitDiffContextHighlight = { bg = "#2d3a50" },
    NeogitDiffDelete = { fg = "#eb6f92" },
    NeogitDiffDeleteHighlight = { bg = "#4b3148" },
    NeogitHunkHeader = { bg = "#373354", fg = "#569fba" },
    NeogitHunkHeaderHighlight = { bg = "#433c59", fg = "#569fba" },
    NeogitNotificationError = { fg = "#eb6f92" },
    NeogitNotificationInfo = { fg = "#569fba" },
    NeogitNotificationWarning = { fg = "#f6c177" },
    NeogitRemote = { fg = "#a3be8c" },
    NonText = { fg = "#4B4673" },
    Normal = { bg = "#232136", fg = "#e0def4" },
    NormalFloat = { bg = "#191726", fg = "#e0def4" },
    NormalNC = { bg = "#232136", fg = "#e0def4" },
    Number = { fg = "#ea9a97", style = "NONE" },
    NvimTreeEmptyFolderName = { fg = "#555169" },
    NvimTreeFolderIcon = { fg = "#569fba" },
    NvimTreeFolderName = { fg = "#569fba" },
    NvimTreeGitDeleted = { fg = "#eb6f92" },
    NvimTreeGitDirty = { fg = "#f6c177" },
    NvimTreeGitNew = { fg = "#a3be8c" },
    NvimTreeImageFile = { fg = "#b1acde" },
    NvimTreeIndentMarker = { fg = "#4B4673" },
    NvimTreeNormal = { bg = "#191726", fg = "#e0def4" },
    NvimTreeOpenedFile = { fg = "#f0a6cc" },
    NvimTreeOpenedFolderName = { fg = "#65b1cd" },
    NvimTreeRootFolder = { fg = "#ea9a97", style = "bold" },
    NvimTreeSpecialFile = { fg = "#9ccfd8" },
    NvimTreeSymlink = { fg = "#d871a6" },
    Operator = { fg = "#D3D1E6" },
    Pmenu = { bg = "#433c59", fg = "#e0def4" },
    PmenuSel = { bg = "#2d3a50" },
    PmenuThumb = { bg = "#2d3a50" },
    PreProc = { fg = "#f0a6cc" },
    Search = { bg = "#2d3a50", fg = "#e0def4" },
    SignColumn = { fg = "#555169" },
    Sneak = { bg = "#c4a7e7", fg = "#191726" },
    SneakScope = { bg = "#433c59" },
    Special = { fg = "#65b1cd" },
    SpellBad = { sp = "#eb6f92", style = "undercurl" },
    SpellCap = { sp = "#f6c177", style = "undercurl" },
    SpellLocal = { sp = "#569fba", style = "undercurl" },
    SpellRare = { sp = "#569fba", style = "undercurl" },
    Statement = { fg = "#c4a7e7", style = "NONE" },
    StatusLine = { bg = "#191726", fg = "#D3D1E6" },
    StatusLineNC = { bg = "#191726", fg = "#555169" },
    String = { fg = "#a3be8c", style = "NONE" },
    Substitute = { bg = "#eb6f92", fg = "#232136" },
    TSConstBuiltin = { fg = "#f0a4a2" },
    TSConstructor = { fg = "#c4a7e7" },
    TSDanger = { fg = "#eb6f92" },
    TSError = { fg = "#eb6f92" },
    TSField = { fg = "#569fba" },
    TSFuncBuiltin = { fg = "#eb6f92" },
    TSFuncMacro = { fg = "#eb6f92" },
    TSKeywordFunction = { fg = "#eb6f92", style = "NONE" },
    TSKeywordOperator = { fg = "#D3D1E6", style = "bold" },
    TSNamespace = { fg = "#a6dae3" },
    TSNote = { fg = "#569fba" },
    TSOperator = { fg = "#D3D1E6" },
    TSPunctBracket = { fg = "#D3D1E6" },
    TSPunctDelimiter = { fg = "#D3D1E6" },
    TSPunctSpecial = { fg = "#D3D1E6" },
    TSStringEscape = { fg = "#f9cb8c", style = "bold" },
    TSStringRegex = { fg = "#f9cb8c", style = "NONE" },
    TSTextReference = { fg = "#c4a7e7" },
    TSTypeBuiltin = { fg = "#a6dae3", style = "NONE" },
    TSURI = { fg = "#9ccfd8", style = "bold" },
    TSVariable = { fg = "#e0def4", style = "NONE" },
    TSVariableBuiltin = { fg = "#eb6f92", style = "NONE" },
    TSWarning = { fg = "#f6c177" },
    TabLine = { bg = "#2D2A45", fg = "#555169" },
    TabLineFill = { bg = "#191726" },
    TabLineSel = { bg = "#4B4673", fg = "#D3D1E6" },
    TelescopeBorder = { fg = "#4B4673" },
    TelescopeMatching = { bg = "#2d3a50", fg = "#e0def4" },
    TelescopeSelection = { bg = "#433c59" },
    TelescopeSelectionCaret = { fg = "#a3be8c" },
    Title = { fg = "#65b1cd" },
    Todo = { bg = "#569fba", fg = "#232136" },
    Type = { fg = "#f6c177", style = "NONE" },
    Underlined = { style = "underline" },
    VertSplit = { fg = "#4B4673" },
    Visual = { bg = "#433c59" },
    WarningMsg = { fg = "#f6c177" },
    WhichKeyFloat = { bg = "#191726" },
    Whitespace = { fg = "#2D2A45" },
    diffAdded = { fg = "#a3be8c" },
    diffChanged = { fg = "#f6c177" },
    diffFile = { fg = "#569fba" },
    diffIndexLine = { fg = "#f0a6cc" },
    diffLine = { fg = "#f0a4a2" },
    diffNewFile = { fg = "#a3be8c" },
    diffOldFile = { fg = "#f6c177" },
    diffRemoved = { fg = "#eb6f92" },
    rainboecol1 = { fg = "#eb6f92" },
    rainboecol2 = { fg = "#f6c177" },
    rainboecol3 = { fg = "#a3be8c" },
    rainboecol4 = { fg = "#569fba" },
    rainboecol5 = { fg = "#9ccfd8" },
    rainboecol6 = { fg = "#c4a7e7" },
    rainboecol7 = { fg = "#eb98c3" },
    rustTSField = { fg = "#D3D1E6" },
  },
  nightfox = {
    Bold = { style = "bold" },
    BufferCurrent = { bg = "#71839b", fg = "#cdcecf" },
    BufferCurrentIndex = { bg = "#71839b", fg = "#719cd6" },
    BufferCurrentMod = { bg = "#71839b", fg = "#dbc074" },
    BufferCurrentSign = { bg = "#71839b", fg = "#719cd6" },
    BufferCurrentTarget = { bg = "#71839b", fg = "#c94f6d" },
    BufferInactive = { bg = "#131a24", fg = "#526176" },
    BufferInactiveIndex = { bg = "#131a24", fg = "#526176" },
    BufferInactiveMod = { bg = "#131a24", fg = "#40423e" },
    BufferInactiveSign = { bg = "#131a24", fg = "#29394e" },
    BufferInactiveTarget = { bg = "#131a24", fg = "#c94f6d" },
    BufferTabpage = { bg = "#131a24", fg = "#29394e" },
    BufferTabpages = { bg = "#131a24" },
    BufferVisible = { bg = "#131a24", fg = "#cdcecf" },
    BufferVisibleIndex = { bg = "#131a24", fg = "#719cd6" },
    BufferVisibleMod = { bg = "#131a24", fg = "#dbc074" },
    BufferVisibleSign = { bg = "#131a24", fg = "#719cd6" },
    BufferVisibleTarget = { bg = "#131a24", fg = "#c94f6d" },
    CmpDocumentation = { bg = "#131a24", fg = "#cdcecf" },
    CmpDocumentationBorder = { bg = "#131a24", fg = "#223249" },
    CmpItemAbbr = { fg = "#cdcecf" },
    CmpItemAbbrDeprecated = { fg = "#71839b", style = "strikethrough" },
    CmpItemAbbrMatch = { fg = "#86abdc" },
    CmpItemAbbrMatchFuzzy = { fg = "#86abdc" },
    CmpItemKindDefault = { fg = "#aeafb0" },
    CmpItemKindSnippet = { fg = "#aeafb0" },
    ColorColumn = { bg = "#212e3f" },
    Comment = { fg = "#526176", style = "NONE" },
    Conceal = { fg = "#3c4b5e" },
    Conditional = { fg = "#baa1e2" },
    Constant = { fg = "#f6b079" },
    Cursor = { bg = "#cdcecf", fg = "#192330" },
    CursorColumn = { bg = "#29394e" },
    CursorLineNr = { fg = "#dbc074", style = "bold" },
    DashboardFooter = { fg = "#f6b079", style = "italic" },
    DiagnosticError = { fg = "#c94f6d" },
    DiagnosticHint = { fg = "#81b29a" },
    DiagnosticInfo = { fg = "#719cd6" },
    DiagnosticUnderlineError = { sp = "#c94f6d", style = "undercurl" },
    DiagnosticUnderlineHint = { sp = "#81b29a", style = "undercurl" },
    DiagnosticUnderlineInfo = { sp = "#719cd6", style = "undercurl" },
    DiagnosticUnderlineWarn = { sp = "#dbc074", style = "undercurl" },
    DiagnosticVirtualTextError = { bg = "#3c2c3c", fg = "#c94f6d" },
    DiagnosticVirtualTextHint = { bg = "#2e4045", fg = "#81b29a" },
    DiagnosticVirtualTextInfo = { bg = "#2b3b51", fg = "#719cd6" },
    DiagnosticVirtualTextWarn = { bg = "#40423e", fg = "#dbc074" },
    DiagnosticWarn = { fg = "#dbc074" },
    DiffAdd = { bg = "#26343c" },
    DiffChange = { bg = "#243244" },
    DiffDelete = { bg = "#2f2837" },
    DiffText = { bg = "#253f4a" },
    Directory = { fg = "#86abdc" },
    EndOfBuffer = { fg = "#192330" },
    Error = { fg = "#c94f6d" },
    ErrorMsg = { fg = "#c94f6d" },
    FernBranchText = { fg = "#719cd6" },
    FloatBorder = { fg = "#71839b" },
    FoldColumn = { fg = "#29394e" },
    Folded = { bg = "#29394e", fg = "#71839b" },
    Function = { fg = "#86abdc", style = "NONE" },
    GitGutterAdd = { fg = "#81b29a" },
    GitGutterChange = { fg = "#dbc074" },
    GitGutterDelete = { fg = "#c94f6d" },
    GitSignsAdd = { fg = "#81b29a" },
    GitSignsChange = { fg = "#c94f6d" },
    GitSignsDelete = { fg = "#dbc074" },
    GlyphPallet0 = { fg = "#393b44" },
    GlyphPallet1 = { fg = "#c94f6d" },
    GlyphPallet10 = { fg = "#8ebaa4" },
    GlyphPallet11 = { fg = "#e0c989" },
    GlyphPallet12 = { fg = "#86abdc" },
    GlyphPallet13 = { fg = "#baa1e2" },
    GlyphPallet14 = { fg = "#7ad4d6" },
    GlyphPallet15 = { fg = "#e4e4e5" },
    GlyphPallet2 = { fg = "#81b29a" },
    GlyphPallet3 = { fg = "#dbc074" },
    GlyphPallet4 = { fg = "#719cd6" },
    GlyphPallet5 = { fg = "#9d79d6" },
    GlyphPallet6 = { fg = "#63cdcf" },
    GlyphPallet7 = { fg = "#e4e4e5" },
    GlyphPallet8 = { fg = "#575860" },
    GlyphPallet9 = { fg = "#d16983" },
    HopNextKey = { fg = "#63cdcf", style = "bold" },
    HopNextKey1 = { fg = "#719cd6", style = "bold" },
    HopNextKey2 = { fg = "#6085b6" },
    HopUnmatched = { fg = "#526176" },
    Identifier = { fg = "#63cdcf", style = "NONE" },
    IncSearch = { bg = "#81b29a", fg = "#3a567d" },
    Italic = { style = "italic" },
    Keyword = { fg = "#9d79d6", style = "NONE" },
    LightspeedGreyWash = { fg = "#526176" },
    LineNr = { fg = "#71839b" },
    LspCodeLens = { fg = "#526176" },
    LspCodeLensSeparator = { fg = "#71839b" },
    LspFloatWinBorder = { fg = "#71839b" },
    LspFloatWinNormal = { bg = "#131a24" },
    LspReferenceRead = { bg = "#223249" },
    LspReferenceText = { bg = "#223249" },
    LspReferenceWrite = { bg = "#223249" },
    LspSagaCodeActionBorder = { fg = "#71839b" },
    LspSagaDefPreviewBorder = { fg = "#71839b" },
    LspSagaFinderSelection = { fg = "#223249" },
    LspSagaHoverBorder = { fg = "#71839b" },
    LspSagaRenameBorder = { fg = "#71839b" },
    LspSagaSignatureHelpBorder = { fg = "#c94f6d" },
    LspSignatureActiveParameter = { fg = "#3a567d" },
    LspTroubleCount = { bg = "#71839b", fg = "#9d79d6" },
    LspTroubleNormal = { bg = "#131a24", fg = "#71839b" },
    LspTroubleText = { fg = "#aeafb0" },
    MatchParen = { fg = "#dbc074", style = "bold" },
    ModeMsg = { fg = "#dbc074", style = "bold" },
    MoreMsg = { fg = "#719cd6", style = "bold" },
    MsgArea = { fg = "#aeafb0" },
    NeogitBranch = { fg = "#dbc074" },
    NeogitDiffAdd = { fg = "#81b29a" },
    NeogitDiffAddHighlight = { bg = "#26343c" },
    NeogitDiffContextHighlight = { bg = "#243244" },
    NeogitDiffDelete = { fg = "#c94f6d" },
    NeogitDiffDeleteHighlight = { bg = "#2f2837" },
    NeogitHunkHeader = { bg = "#29394e", fg = "#719cd6" },
    NeogitHunkHeaderHighlight = { bg = "#223249", fg = "#719cd6" },
    NeogitNotificationError = { fg = "#c94f6d" },
    NeogitNotificationInfo = { fg = "#719cd6" },
    NeogitNotificationWarning = { fg = "#dbc074" },
    NeogitRemote = { fg = "#81b29a" },
    NonText = { fg = "#3c4b5e" },
    Normal = { bg = "#192330", fg = "#cdcecf" },
    NormalFloat = { bg = "#131a24", fg = "#cdcecf" },
    NormalNC = { bg = "#192330", fg = "#cdcecf" },
    Number = { fg = "#f4a261", style = "NONE" },
    NvimTreeEmptyFolderName = { fg = "#71839b" },
    NvimTreeFolderIcon = { fg = "#719cd6" },
    NvimTreeFolderName = { fg = "#719cd6" },
    NvimTreeGitDeleted = { fg = "#c94f6d" },
    NvimTreeGitDirty = { fg = "#dbc074" },
    NvimTreeGitNew = { fg = "#81b29a" },
    NvimTreeImageFile = { fg = "#bebebe" },
    NvimTreeIndentMarker = { fg = "#3c4b5e" },
    NvimTreeNormal = { bg = "#131a24", fg = "#cdcecf" },
    NvimTreeOpenedFile = { fg = "#dc8ed9" },
    NvimTreeOpenedFolderName = { fg = "#86abdc" },
    NvimTreeRootFolder = { fg = "#f4a261", style = "bold" },
    NvimTreeSpecialFile = { fg = "#63cdcf" },
    NvimTreeSymlink = { fg = "#b668b2" },
    Operator = { fg = "#aeafb0" },
    Pmenu = { bg = "#223249", fg = "#cdcecf" },
    PmenuSel = { bg = "#3a567d" },
    PmenuThumb = { bg = "#3a567d" },
    PreProc = { fg = "#dc8ed9" },
    Search = { bg = "#3a567d", fg = "#cdcecf" },
    SignColumn = { fg = "#71839b" },
    Sneak = { bg = "#9d79d6", fg = "#131a24" },
    SneakScope = { bg = "#223249" },
    Special = { fg = "#86abdc" },
    SpellBad = { sp = "#c94f6d", style = "undercurl" },
    SpellCap = { sp = "#dbc074", style = "undercurl" },
    SpellLocal = { sp = "#719cd6", style = "undercurl" },
    SpellRare = { sp = "#719cd6", style = "undercurl" },
    Statement = { fg = "#9d79d6", style = "NONE" },
    StatusLine = { bg = "#131a24", fg = "#aeafb0" },
    StatusLineNC = { bg = "#131a24", fg = "#71839b" },
    String = { fg = "#81b29a", style = "NONE" },
    Substitute = { bg = "#c94f6d", fg = "#192330" },
    TSConstBuiltin = { fg = "#f6b079" },
    TSConstructor = { fg = "#9d79d6" },
    TSDanger = { fg = "#c94f6d" },
    TSError = { fg = "#c94f6d" },
    TSField = { fg = "#719cd6" },
    TSFuncBuiltin = { fg = "#c94f6d" },
    TSFuncMacro = { fg = "#c94f6d" },
    TSKeywordFunction = { fg = "#c94f6d", style = "NONE" },
    TSKeywordOperator = { fg = "#aeafb0", style = "bold" },
    TSNamespace = { fg = "#7ad4d6" },
    TSNote = { fg = "#719cd6" },
    TSOperator = { fg = "#aeafb0" },
    TSPunctBracket = { fg = "#aeafb0" },
    TSPunctDelimiter = { fg = "#aeafb0" },
    TSPunctSpecial = { fg = "#aeafb0" },
    TSStringEscape = { fg = "#e0c989", style = "bold" },
    TSStringRegex = { fg = "#e0c989", style = "NONE" },
    TSTextReference = { fg = "#9d79d6" },
    TSTypeBuiltin = { fg = "#7ad4d6", style = "NONE" },
    TSURI = { fg = "#63cdcf", style = "bold" },
    TSVariable = { fg = "#dfdfe0", style = "NONE" },
    TSVariableBuiltin = { fg = "#c94f6d", style = "NONE" },
    TSWarning = { fg = "#dbc074" },
    TabLine = { bg = "#212e3f", fg = "#71839b" },
    TabLineFill = { bg = "#131a24" },
    TabLineSel = { bg = "#3c4b5e", fg = "#aeafb0" },
    TelescopeBorder = { fg = "#3c4b5e" },
    TelescopeMatching = { bg = "#3a567d", fg = "#cdcecf" },
    TelescopeSelection = { bg = "#223249" },
    TelescopeSelectionCaret = { fg = "#81b29a" },
    Title = { fg = "#86abdc" },
    Todo = { bg = "#719cd6", fg = "#192330" },
    Type = { fg = "#dbc074", style = "NONE" },
    Underlined = { style = "underline" },
    VertSplit = { fg = "#3c4b5e" },
    Visual = { bg = "#223249" },
    WarningMsg = { fg = "#dbc074" },
    WhichKeyFloat = { bg = "#131a24" },
    Whitespace = { fg = "#212e3f" },
    diffAdded = { fg = "#81b29a" },
    diffChanged = { fg = "#dbc074" },
    diffFile = { fg = "#719cd6" },
    diffIndexLine = { fg = "#dc8ed9" },
    diffLine = { fg = "#f6b079" },
    diffNewFile = { fg = "#81b29a" },
    diffOldFile = { fg = "#dbc074" },
    diffRemoved = { fg = "#c94f6d" },
    rainboecol1 = { fg = "#c94f6d" },
    rainboecol2 = { fg = "#dbc074" },
    rainboecol3 = { fg = "#81b29a" },
    rainboecol4 = { fg = "#719cd6" },
    rainboecol5 = { fg = "#63cdcf" },
    rainboecol6 = { fg = "#9d79d6" },
    rainboecol7 = { fg = "#d67ad2" },
    rustTSField = { fg = "#aeafb0" },
  },
  nordfox = {
    Bold = { style = "bold" },
    BufferCurrent = { bg = "#7e8188", fg = "#cdcecf" },
    BufferCurrentIndex = { bg = "#7e8188", fg = "#81a1c1" },
    BufferCurrentMod = { bg = "#7e8188", fg = "#ebcb8b" },
    BufferCurrentSign = { bg = "#7e8188", fg = "#81a1c1" },
    BufferCurrentTarget = { bg = "#7e8188", fg = "#bf616a" },
    BufferInactive = { bg = "#232831", fg = "#60728a" },
    BufferInactiveIndex = { bg = "#232831", fg = "#60728a" },
    BufferInactiveMod = { bg = "#232831", fg = "#54524f" },
    BufferInactiveSign = { bg = "#232831", fg = "#444c5e" },
    BufferInactiveTarget = { bg = "#232831", fg = "#bf616a" },
    BufferTabpage = { bg = "#232831", fg = "#444c5e" },
    BufferTabpages = { bg = "#232831" },
    BufferVisible = { bg = "#232831", fg = "#cdcecf" },
    BufferVisibleIndex = { bg = "#232831", fg = "#81a1c1" },
    BufferVisibleMod = { bg = "#232831", fg = "#ebcb8b" },
    BufferVisibleSign = { bg = "#232831", fg = "#81a1c1" },
    BufferVisibleTarget = { bg = "#232831", fg = "#bf616a" },
    CmpDocumentation = { bg = "#232831", fg = "#cdcecf" },
    CmpDocumentationBorder = { bg = "#232831", fg = "#3e4a5b" },
    CmpItemAbbr = { fg = "#cdcecf" },
    CmpItemAbbrDeprecated = { fg = "#7e8188", style = "strikethrough" },
    CmpItemAbbrMatch = { fg = "#8cafd2" },
    CmpItemAbbrMatchFuzzy = { fg = "#8cafd2" },
    CmpItemKindDefault = { fg = "#abb1bb" },
    CmpItemKindSnippet = { fg = "#abb1bb" },
    ColorColumn = { bg = "#39404f" },
    Comment = { fg = "#60728a", style = "NONE" },
    Conceal = { fg = "#5a657d" },
    Conditional = { fg = "#c895bf" },
    Constant = { fg = "#d89079" },
    Cursor = { bg = "#cdcecf", fg = "#2e3440" },
    CursorColumn = { bg = "#444c5e" },
    CursorLineNr = { fg = "#ebcb8b", style = "bold" },
    DashboardFooter = { fg = "#d89079", style = "italic" },
    DiagnosticError = { fg = "#bf616a" },
    DiagnosticHint = { fg = "#a3be8c" },
    DiagnosticInfo = { fg = "#81a1c1" },
    DiagnosticUnderlineError = { sp = "#bf616a", style = "undercurl" },
    DiagnosticUnderlineHint = { sp = "#a3be8c", style = "undercurl" },
    DiagnosticUnderlineInfo = { sp = "#81a1c1", style = "undercurl" },
    DiagnosticUnderlineWarn = { sp = "#ebcb8b", style = "undercurl" },
    DiagnosticVirtualTextError = { bg = "#4b3d48", fg = "#bf616a" },
    DiagnosticVirtualTextHint = { bg = "#45504f", fg = "#a3be8c" },
    DiagnosticVirtualTextInfo = { bg = "#3f4a5a", fg = "#81a1c1" },
    DiagnosticVirtualTextWarn = { bg = "#54524f", fg = "#ebcb8b" },
    DiagnosticWarn = { fg = "#ebcb8b" },
    DiffAdd = { bg = "#3c4548" },
    DiffChange = { bg = "#364150" },
    DiffDelete = { bg = "#403843" },
    DiffText = { bg = "#3d515e" },
    Directory = { fg = "#8cafd2" },
    EndOfBuffer = { fg = "#2e3440" },
    Error = { fg = "#bf616a" },
    ErrorMsg = { fg = "#bf616a" },
    FernBranchText = { fg = "#81a1c1" },
    FloatBorder = { fg = "#7e8188" },
    FoldColumn = { fg = "#444c5e" },
    Folded = { bg = "#444c5e", fg = "#7e8188" },
    Function = { fg = "#8cafd2", style = "NONE" },
    GitGutterAdd = { fg = "#a3be8c" },
    GitGutterChange = { fg = "#ebcb8b" },
    GitGutterDelete = { fg = "#bf616a" },
    GitSignsAdd = { fg = "#a3be8c" },
    GitSignsChange = { fg = "#bf616a" },
    GitSignsDelete = { fg = "#ebcb8b" },
    GlyphPallet0 = { fg = "#3b4252" },
    GlyphPallet1 = { fg = "#bf616a" },
    GlyphPallet10 = { fg = "#b1d196" },
    GlyphPallet11 = { fg = "#f0d399" },
    GlyphPallet12 = { fg = "#8cafd2" },
    GlyphPallet13 = { fg = "#c895bf" },
    GlyphPallet14 = { fg = "#93ccdc" },
    GlyphPallet15 = { fg = "#e7ecf4" },
    GlyphPallet2 = { fg = "#a3be8c" },
    GlyphPallet3 = { fg = "#ebcb8b" },
    GlyphPallet4 = { fg = "#81a1c1" },
    GlyphPallet5 = { fg = "#b48ead" },
    GlyphPallet6 = { fg = "#88c0d0" },
    GlyphPallet7 = { fg = "#e7ecf4" },
    GlyphPallet8 = { fg = "#465780" },
    GlyphPallet9 = { fg = "#d06f79" },
    HopNextKey = { fg = "#88c0d0", style = "bold" },
    HopNextKey1 = { fg = "#81a1c1", style = "bold" },
    HopNextKey2 = { fg = "#668aab" },
    HopUnmatched = { fg = "#60728a" },
    Identifier = { fg = "#88c0d0", style = "NONE" },
    IncSearch = { bg = "#a3be8c", fg = "#4f6074" },
    Italic = { style = "italic" },
    Keyword = { fg = "#b48ead", style = "NONE" },
    LightspeedGreyWash = { fg = "#60728a" },
    LineNr = { fg = "#7e8188" },
    LspCodeLens = { fg = "#60728a" },
    LspCodeLensSeparator = { fg = "#7e8188" },
    LspFloatWinBorder = { fg = "#7e8188" },
    LspFloatWinNormal = { bg = "#232831" },
    LspReferenceRead = { bg = "#3e4a5b" },
    LspReferenceText = { bg = "#3e4a5b" },
    LspReferenceWrite = { bg = "#3e4a5b" },
    LspSagaCodeActionBorder = { fg = "#7e8188" },
    LspSagaDefPreviewBorder = { fg = "#7e8188" },
    LspSagaFinderSelection = { fg = "#3e4a5b" },
    LspSagaHoverBorder = { fg = "#7e8188" },
    LspSagaRenameBorder = { fg = "#7e8188" },
    LspSagaSignatureHelpBorder = { fg = "#bf616a" },
    LspSignatureActiveParameter = { fg = "#4f6074" },
    LspTroubleCount = { bg = "#7e8188", fg = "#b48ead" },
    LspTroubleNormal = { bg = "#232831", fg = "#7e8188" },
    LspTroubleText = { fg = "#abb1bb" },
    MatchParen = { fg = "#ebcb8b", style = "bold" },
    ModeMsg = { fg = "#ebcb8b", style = "bold" },
    MoreMsg = { fg = "#81a1c1", style = "bold" },
    MsgArea = { fg = "#abb1bb" },
    NeogitBranch = { fg = "#ebcb8b" },
    NeogitDiffAdd = { fg = "#a3be8c" },
    NeogitDiffAddHighlight = { bg = "#3c4548" },
    NeogitDiffContextHighlight = { bg = "#364150" },
    NeogitDiffDelete = { fg = "#bf616a" },
    NeogitDiffDeleteHighlight = { bg = "#403843" },
    NeogitHunkHeader = { bg = "#444c5e", fg = "#81a1c1" },
    NeogitHunkHeaderHighlight = { bg = "#3e4a5b", fg = "#81a1c1" },
    NeogitNotificationError = { fg = "#bf616a" },
    NeogitNotificationInfo = { fg = "#81a1c1" },
    NeogitNotificationWarning = { fg = "#ebcb8b" },
    NeogitRemote = { fg = "#a3be8c" },
    NonText = { fg = "#5a657d" },
    Normal = { bg = "#2e3440", fg = "#cdcecf" },
    NormalFloat = { bg = "#232831", fg = "#cdcecf" },
    NormalNC = { bg = "#2e3440", fg = "#cdcecf" },
    Number = { fg = "#c9826b", style = "NONE" },
    NvimTreeEmptyFolderName = { fg = "#7e8188" },
    NvimTreeFolderIcon = { fg = "#81a1c1" },
    NvimTreeFolderName = { fg = "#81a1c1" },
    NvimTreeGitDeleted = { fg = "#bf616a" },
    NvimTreeGitDirty = { fg = "#ebcb8b" },
    NvimTreeGitNew = { fg = "#a3be8c" },
    NvimTreeImageFile = { fg = "#bbc3d4" },
    NvimTreeIndentMarker = { fg = "#5a657d" },
    NvimTreeNormal = { bg = "#232831", fg = "#cdcecf" },
    NvimTreeOpenedFile = { fg = "#d092ce" },
    NvimTreeOpenedFolderName = { fg = "#8cafd2" },
    NvimTreeRootFolder = { fg = "#c9826b", style = "bold" },
    NvimTreeSpecialFile = { fg = "#88c0d0" },
    NvimTreeSymlink = { fg = "#a96ca5" },
    Operator = { fg = "#abb1bb" },
    Pmenu = { bg = "#3e4a5b", fg = "#cdcecf" },
    PmenuSel = { bg = "#4f6074" },
    PmenuThumb = { bg = "#4f6074" },
    PreProc = { fg = "#d092ce" },
    Search = { bg = "#4f6074", fg = "#cdcecf" },
    SignColumn = { fg = "#7e8188" },
    Sneak = { bg = "#b48ead", fg = "#232831" },
    SneakScope = { bg = "#3e4a5b" },
    Special = { fg = "#8cafd2" },
    SpellBad = { sp = "#bf616a", style = "undercurl" },
    SpellCap = { sp = "#ebcb8b", style = "undercurl" },
    SpellLocal = { sp = "#81a1c1", style = "undercurl" },
    SpellRare = { sp = "#81a1c1", style = "undercurl" },
    Statement = { fg = "#b48ead", style = "NONE" },
    StatusLine = { bg = "#232831", fg = "#abb1bb" },
    StatusLineNC = { bg = "#232831", fg = "#7e8188" },
    String = { fg = "#a3be8c", style = "NONE" },
    Substitute = { bg = "#bf616a", fg = "#2e3440" },
    TSConstBuiltin = { fg = "#d89079" },
    TSConstructor = { fg = "#b48ead" },
    TSDanger = { fg = "#bf616a" },
    TSError = { fg = "#bf616a" },
    TSField = { fg = "#81a1c1" },
    TSFuncBuiltin = { fg = "#bf616a" },
    TSFuncMacro = { fg = "#bf616a" },
    TSKeywordFunction = { fg = "#bf616a", style = "NONE" },
    TSKeywordOperator = { fg = "#abb1bb", style = "bold" },
    TSNamespace = { fg = "#93ccdc" },
    TSNote = { fg = "#81a1c1" },
    TSOperator = { fg = "#abb1bb" },
    TSPunctBracket = { fg = "#abb1bb" },
    TSPunctDelimiter = { fg = "#abb1bb" },
    TSPunctSpecial = { fg = "#abb1bb" },
    TSStringEscape = { fg = "#f0d399", style = "bold" },
    TSStringRegex = { fg = "#f0d399", style = "NONE" },
    TSTextReference = { fg = "#b48ead" },
    TSTypeBuiltin = { fg = "#93ccdc", style = "NONE" },
    TSURI = { fg = "#88c0d0", style = "bold" },
    TSVariable = { fg = "#e5e9f0", style = "NONE" },
    TSVariableBuiltin = { fg = "#bf616a", style = "NONE" },
    TSWarning = { fg = "#ebcb8b" },
    TabLine = { bg = "#39404f", fg = "#7e8188" },
    TabLineFill = { bg = "#232831" },
    TabLineSel = { bg = "#5a657d", fg = "#abb1bb" },
    TelescopeBorder = { fg = "#5a657d" },
    TelescopeMatching = { bg = "#4f6074", fg = "#cdcecf" },
    TelescopeSelection = { bg = "#3e4a5b" },
    TelescopeSelectionCaret = { fg = "#a3be8c" },
    Title = { fg = "#8cafd2" },
    Todo = { bg = "#81a1c1", fg = "#2e3440" },
    Type = { fg = "#ebcb8b", style = "NONE" },
    Underlined = { style = "underline" },
    VertSplit = { fg = "#5a657d" },
    Visual = { bg = "#3e4a5b" },
    WarningMsg = { fg = "#ebcb8b" },
    WhichKeyFloat = { bg = "#232831" },
    Whitespace = { fg = "#39404f" },
    diffAdded = { fg = "#a3be8c" },
    diffChanged = { fg = "#ebcb8b" },
    diffFile = { fg = "#81a1c1" },
    diffIndexLine = { fg = "#d092ce" },
    diffLine = { fg = "#d89079" },
    diffNewFile = { fg = "#a3be8c" },
    diffOldFile = { fg = "#ebcb8b" },
    diffRemoved = { fg = "#bf616a" },
    rainboecol1 = { fg = "#bf616a" },
    rainboecol2 = { fg = "#ebcb8b" },
    rainboecol3 = { fg = "#a3be8c" },
    rainboecol4 = { fg = "#81a1c1" },
    rainboecol5 = { fg = "#88c0d0" },
    rainboecol6 = { fg = "#b48ead" },
    rainboecol7 = { fg = "#bf88bc" },
    rustTSField = { fg = "#abb1bb" },
  },
}

local links = {
dawnfox = {
    Boolean = "Number",
    Character = "Character",
    CmpItemKindClass = "Type",
    CmpItemKindConstant = "TSConstant",
    CmpItemKindConstructor = "Function",
    CmpItemKindEnum = "Constant",
    CmpItemKindEnumMember = "TSField",
    CmpItemKindEvent = "Constant",
    CmpItemKindField = "TSField",
    CmpItemKindFunction = "Function",
    CmpItemKindInterface = "Constant",
    CmpItemKindKeyword = "Identifier",
    CmpItemKindMethod = "Function",
    CmpItemKindModule = "TSNamespace",
    CmpItemKindOperator = "Operator",
    CmpItemKindProperty = "TSProperty",
    CmpItemKindReference = "Keyword",
    CmpItemKindStruct = "Type",
    CmpItemKindTypeParameter = "TSField",
    CmpItemKindUnit = "Constant",
    CmpItemKindValue = "Keyword",
    CmpItemKindVariable = "TSVariable",
    CmpItemMenu = "Comment",
    CursorIM = "Cursor",
    CursorLine = "CursorColumn",
    DashboardCenter = "String",
    DashboardHeader = "Title",
    DashboardShortCut = "Identifier",
    Debug = "Special",
    Define = "PreProc",
    Delimiter = "Special",
    DiagnosticSignError = "DiagnosticError",
    DiagnosticSignHint = "DiagnosticHint",
    DiagnosticSignInfo = "DiagnosticInfo",
    DiagnosticSignWarn = "DiagnosticWarn",
    Exception = "Keyword",
    FidgetTask = "LineNr",
    FidgetTitle = "Title",
    Float = "Number",
    Include = "PreProc",
    Label = "Conditional",
    LspSagaBorderTitle = "Title",
    LspSagaCodeActionContent = "String",
    LspSagaCodeActionTitle = "Title",
    Macro = "PreProc",
    NvimTreeVertSplit = "VertSplit",
    PmenuSbar = "Pmenu",
    PreCondit = "PreProc",
    Question = "MoreMsg",
    QuickFixLine = "CursorLine",
    Repeat = "Conditional",
    SignColumnSB = "SignColumn",
    SpecialChar = "Special",
    SpecialComment = "Special",
    SpecialKey = "NonText",
    StorageClass = "Type",
    Structure = "Type",
    TSAttribute = "Constant",
    TSProperty = "TSField",
    Tag = "Special",
    Typedef = "Type",
    VisualNOS = "visual",
    WhichKey = "Identifier",
    WhichKeyDesc = "Keyword",
    WhichKeyGroup = "Function",
    WhichKeySeparator = "Comment",
    WhichKeySeperator = "Comment",
    WhichKeyValue = "Comment",
    WildMenu = "Pmenu",
    illuminatedCurWord = "LspReferenceText",
    illuminatedWord = "LspReferenceText",
    lCursor = "Cursor",
    qfFileName = "Directory",
    qfLineNr = "lineNr",
  },
dayfox = {
    Boolean = "Number",
    Character = "Character",
    CmpItemKindClass = "Type",
    CmpItemKindConstant = "TSConstant",
    CmpItemKindConstructor = "Function",
    CmpItemKindEnum = "Constant",
    CmpItemKindEnumMember = "TSField",
    CmpItemKindEvent = "Constant",
    CmpItemKindField = "TSField",
    CmpItemKindFunction = "Function",
    CmpItemKindInterface = "Constant",
    CmpItemKindKeyword = "Identifier",
    CmpItemKindMethod = "Function",
    CmpItemKindModule = "TSNamespace",
    CmpItemKindOperator = "Operator",
    CmpItemKindProperty = "TSProperty",
    CmpItemKindReference = "Keyword",
    CmpItemKindStruct = "Type",
    CmpItemKindTypeParameter = "TSField",
    CmpItemKindUnit = "Constant",
    CmpItemKindValue = "Keyword",
    CmpItemKindVariable = "TSVariable",
    CmpItemMenu = "Comment",
    CursorIM = "Cursor",
    CursorLine = "CursorColumn",
    DashboardCenter = "String",
    DashboardHeader = "Title",
    DashboardShortCut = "Identifier",
    Debug = "Special",
    Define = "PreProc",
    Delimiter = "Special",
    DiagnosticSignError = "DiagnosticError",
    DiagnosticSignHint = "DiagnosticHint",
    DiagnosticSignInfo = "DiagnosticInfo",
    DiagnosticSignWarn = "DiagnosticWarn",
    Exception = "Keyword",
    FidgetTask = "LineNr",
    FidgetTitle = "Title",
    Float = "Number",
    Include = "PreProc",
    Label = "Conditional",
    LspSagaBorderTitle = "Title",
    LspSagaCodeActionContent = "String",
    LspSagaCodeActionTitle = "Title",
    Macro = "PreProc",
    NvimTreeVertSplit = "VertSplit",
    PmenuSbar = "Pmenu",
    PreCondit = "PreProc",
    Question = "MoreMsg",
    QuickFixLine = "CursorLine",
    Repeat = "Conditional",
    SignColumnSB = "SignColumn",
    SpecialChar = "Special",
    SpecialComment = "Special",
    SpecialKey = "NonText",
    StorageClass = "Type",
    Structure = "Type",
    TSAttribute = "Constant",
    TSProperty = "TSField",
    Tag = "Special",
    Typedef = "Type",
    VisualNOS = "visual",
    WhichKey = "Identifier",
    WhichKeyDesc = "Keyword",
    WhichKeyGroup = "Function",
    WhichKeySeparator = "Comment",
    WhichKeySeperator = "Comment",
    WhichKeyValue = "Comment",
    WildMenu = "Pmenu",
    illuminatedCurWord = "LspReferenceText",
    illuminatedWord = "LspReferenceText",
    lCursor = "Cursor",
    qfFileName = "Directory",
    qfLineNr = "lineNr",
  },
duskfox = {
    Boolean = "Number",
    Character = "Character",
    CmpItemKindClass = "Type",
    CmpItemKindConstant = "TSConstant",
    CmpItemKindConstructor = "Function",
    CmpItemKindEnum = "Constant",
    CmpItemKindEnumMember = "TSField",
    CmpItemKindEvent = "Constant",
    CmpItemKindField = "TSField",
    CmpItemKindFunction = "Function",
    CmpItemKindInterface = "Constant",
    CmpItemKindKeyword = "Identifier",
    CmpItemKindMethod = "Function",
    CmpItemKindModule = "TSNamespace",
    CmpItemKindOperator = "Operator",
    CmpItemKindProperty = "TSProperty",
    CmpItemKindReference = "Keyword",
    CmpItemKindStruct = "Type",
    CmpItemKindTypeParameter = "TSField",
    CmpItemKindUnit = "Constant",
    CmpItemKindValue = "Keyword",
    CmpItemKindVariable = "TSVariable",
    CmpItemMenu = "Comment",
    CursorIM = "Cursor",
    CursorLine = "CursorColumn",
    DashboardCenter = "String",
    DashboardHeader = "Title",
    DashboardShortCut = "Identifier",
    Debug = "Special",
    Define = "PreProc",
    Delimiter = "Special",
    DiagnosticSignError = "DiagnosticError",
    DiagnosticSignHint = "DiagnosticHint",
    DiagnosticSignInfo = "DiagnosticInfo",
    DiagnosticSignWarn = "DiagnosticWarn",
    Exception = "Keyword",
    FidgetTask = "LineNr",
    FidgetTitle = "Title",
    Float = "Number",
    Include = "PreProc",
    Label = "Conditional",
    LspSagaBorderTitle = "Title",
    LspSagaCodeActionContent = "String",
    LspSagaCodeActionTitle = "Title",
    Macro = "PreProc",
    NvimTreeVertSplit = "VertSplit",
    PmenuSbar = "Pmenu",
    PreCondit = "PreProc",
    Question = "MoreMsg",
    QuickFixLine = "CursorLine",
    Repeat = "Conditional",
    SignColumnSB = "SignColumn",
    SpecialChar = "Special",
    SpecialComment = "Special",
    SpecialKey = "NonText",
    StorageClass = "Type",
    Structure = "Type",
    TSAttribute = "Constant",
    TSProperty = "TSField",
    Tag = "Special",
    Typedef = "Type",
    VisualNOS = "visual",
    WhichKey = "Identifier",
    WhichKeyDesc = "Keyword",
    WhichKeyGroup = "Function",
    WhichKeySeparator = "Comment",
    WhichKeySeperator = "Comment",
    WhichKeyValue = "Comment",
    WildMenu = "Pmenu",
    illuminatedCurWord = "LspReferenceText",
    illuminatedWord = "LspReferenceText",
    lCursor = "Cursor",
    qfFileName = "Directory",
    qfLineNr = "lineNr",
  },
nightfox = {
    Boolean = "Number",
    Character = "Character",
    CmpItemKindClass = "Type",
    CmpItemKindConstant = "TSConstant",
    CmpItemKindConstructor = "Function",
    CmpItemKindEnum = "Constant",
    CmpItemKindEnumMember = "TSField",
    CmpItemKindEvent = "Constant",
    CmpItemKindField = "TSField",
    CmpItemKindFunction = "Function",
    CmpItemKindInterface = "Constant",
    CmpItemKindKeyword = "Identifier",
    CmpItemKindMethod = "Function",
    CmpItemKindModule = "TSNamespace",
    CmpItemKindOperator = "Operator",
    CmpItemKindProperty = "TSProperty",
    CmpItemKindReference = "Keyword",
    CmpItemKindStruct = "Type",
    CmpItemKindTypeParameter = "TSField",
    CmpItemKindUnit = "Constant",
    CmpItemKindValue = "Keyword",
    CmpItemKindVariable = "TSVariable",
    CmpItemMenu = "Comment",
    CursorIM = "Cursor",
    CursorLine = "CursorColumn",
    DashboardCenter = "String",
    DashboardHeader = "Title",
    DashboardShortCut = "Identifier",
    Debug = "Special",
    Define = "PreProc",
    Delimiter = "Special",
    DiagnosticSignError = "DiagnosticError",
    DiagnosticSignHint = "DiagnosticHint",
    DiagnosticSignInfo = "DiagnosticInfo",
    DiagnosticSignWarn = "DiagnosticWarn",
    Exception = "Keyword",
    FidgetTask = "LineNr",
    FidgetTitle = "Title",
    Float = "Number",
    Include = "PreProc",
    Label = "Conditional",
    LspSagaBorderTitle = "Title",
    LspSagaCodeActionContent = "String",
    LspSagaCodeActionTitle = "Title",
    Macro = "PreProc",
    NvimTreeVertSplit = "VertSplit",
    PmenuSbar = "Pmenu",
    PreCondit = "PreProc",
    Question = "MoreMsg",
    QuickFixLine = "CursorLine",
    Repeat = "Conditional",
    SignColumnSB = "SignColumn",
    SpecialChar = "Special",
    SpecialComment = "Special",
    SpecialKey = "NonText",
    StorageClass = "Type",
    Structure = "Type",
    TSAttribute = "Constant",
    TSProperty = "TSField",
    Tag = "Special",
    Typedef = "Type",
    VisualNOS = "visual",
    WhichKey = "Identifier",
    WhichKeyDesc = "Keyword",
    WhichKeyGroup = "Function",
    WhichKeySeparator = "Comment",
    WhichKeySeperator = "Comment",
    WhichKeyValue = "Comment",
    WildMenu = "Pmenu",
    illuminatedCurWord = "LspReferenceText",
    illuminatedWord = "LspReferenceText",
    lCursor = "Cursor",
    qfFileName = "Directory",
    qfLineNr = "lineNr",
  },
nordfox = {
    Boolean = "Number",
    Character = "Character",
    CmpItemKindClass = "Type",
    CmpItemKindConstant = "TSConstant",
    CmpItemKindConstructor = "Function",
    CmpItemKindEnum = "Constant",
    CmpItemKindEnumMember = "TSField",
    CmpItemKindEvent = "Constant",
    CmpItemKindField = "TSField",
    CmpItemKindFunction = "Function",
    CmpItemKindInterface = "Constant",
    CmpItemKindKeyword = "Identifier",
    CmpItemKindMethod = "Function",
    CmpItemKindModule = "TSNamespace",
    CmpItemKindOperator = "Operator",
    CmpItemKindProperty = "TSProperty",
    CmpItemKindReference = "Keyword",
    CmpItemKindStruct = "Type",
    CmpItemKindTypeParameter = "TSField",
    CmpItemKindUnit = "Constant",
    CmpItemKindValue = "Keyword",
    CmpItemKindVariable = "TSVariable",
    CmpItemMenu = "Comment",
    CursorIM = "Cursor",
    CursorLine = "CursorColumn",
    DashboardCenter = "String",
    DashboardHeader = "Title",
    DashboardShortCut = "Identifier",
    Debug = "Special",
    Define = "PreProc",
    Delimiter = "Special",
    DiagnosticSignError = "DiagnosticError",
    DiagnosticSignHint = "DiagnosticHint",
    DiagnosticSignInfo = "DiagnosticInfo",
    DiagnosticSignWarn = "DiagnosticWarn",
    Exception = "Keyword",
    FidgetTask = "LineNr",
    FidgetTitle = "Title",
    Float = "Number",
    Include = "PreProc",
    Label = "Conditional",
    LspSagaBorderTitle = "Title",
    LspSagaCodeActionContent = "String",
    LspSagaCodeActionTitle = "Title",
    Macro = "PreProc",
    NvimTreeVertSplit = "VertSplit",
    PmenuSbar = "Pmenu",
    PreCondit = "PreProc",
    Question = "MoreMsg",
    QuickFixLine = "CursorLine",
    Repeat = "Conditional",
    SignColumnSB = "SignColumn",
    SpecialChar = "Special",
    SpecialComment = "Special",
    SpecialKey = "NonText",
    StorageClass = "Type",
    Structure = "Type",
    TSAttribute = "Constant",
    TSProperty = "TSField",
    Tag = "Special",
    Typedef = "Type",
    VisualNOS = "visual",
    WhichKey = "Identifier",
    WhichKeyDesc = "Keyword",
    WhichKeyGroup = "Function",
    WhichKeySeparator = "Comment",
    WhichKeySeperator = "Comment",
    WhichKeyValue = "Comment",
    WildMenu = "Pmenu",
    illuminatedCurWord = "LspReferenceText",
    illuminatedWord = "LspReferenceText",
    lCursor = "Cursor",
    qfFileName = "Directory",
    qfLineNr = "lineNr",
  },
}

local function highlight(list)
  local cmds = {}
  for group, opts in pairs(list) do
    table.insert(cmds, string.format(
      "highlight %s guifg=%s guibg=%s gui=%s guisp=%s",
      group,
      opts.fg or "NONE",
      opts.bg or "NONE",
      opts.style or "NONE",
      opts.sp or "NONE"
    ))
  end
  vim.cmd(table.concat(cmds, "\n"))
end

local function link(list)
  local cmds = {}
  for group, opts in pairs(list) do
    table.insert(cmds, string.format("highlight! link %s %s", group, opts))
  end
  vim.cmd(table.concat(cmds, "\n"))
end

local function clear()
  if vim.g.colors_name then
    vim.cmd("hi clear")
  end
end

local function set_info(name)
  vim.cmd("set background=" .. metas[name])
  vim.cmd("set termguicolors")
  vim.g.colors_name = name
end

local function set_terminal(name)
  local colors = {
    dawnfox = { "#575279", "#b4637a", "#618774", "#ea9d34", "#286983", "#907aa9", "#56949f", "#e5e9f0", "#5f5695", "#c26d85", "#629f81", "#eea846", "#2d81a3", "#9a80b9", "#5ca7b4", "#e6ebf3" },
    dayfox = { "#1d344f", "#b95d76", "#618774", "#ba793e", "#4d688e", "#8e6f98", "#6ca7bd", "#cdd1d5", "#24476f", "#c76882", "#629f81", "#ca884a", "#4e75aa", "#9f75ac", "#74b2c9", "#cfd6dd" },
    duskfox = { "#393552", "#eb6f92", "#a3be8c", "#f6c177", "#569fba", "#c4a7e7", "#9ccfd8", "#e0def4", "#47407d", "#f083a2", "#b1d196", "#f9cb8c", "#65b1cd", "#ccb1ed", "#a6dae3", "#e2e0f7" },
    nightfox = { "#393b44", "#c94f6d", "#81b29a", "#dbc074", "#719cd6", "#9d79d6", "#63cdcf", "#dfdfe0", "#575860", "#d16983", "#8ebaa4", "#e0c989", "#86abdc", "#baa1e2", "#7ad4d6", "#e4e4e5" },
    nordfox = { "#3b4252", "#bf616a", "#a3be8c", "#ebcb8b", "#81a1c1", "#b48ead", "#88c0d0", "#e5e9f0", "#465780", "#d06f79", "#b1d196", "#f0d399", "#8cafd2", "#c895bf", "#93ccdc", "#e7ecf4" },
  }
  for i, c in ipairs(colors[name]) do
    local n = "terminal_color_" .. i - 1
    vim.g[n] = c
  end
  if vim.fn.has("nvim") == 0 then
    vim.g.terminal_ansi_colors = vim.list(colors)
  end
end

function M.load(name)
  clear()
  highlight(highlights[name])
  link(links[name])
  set_info(name)
  set_terminal(name)
end

return M
