name: Tests
on:
  pull_request: ~
  push:
    paths:
      - "lua/*"
      - "test/*"
    branches:
      - main

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Neovim and dependencies
        run: |
          wget -q https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.deb -O /tmp/nvim.deb
          sudo dpkg -i /tmp/nvim.deb
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim test/plenary
      - name: Run tests
        run: |
          nvim --version
          [ ! -d test ] && exit 0
          nvim --headless --noplugin -u test/minimal_init.vim -c "PlenaryBustedDirectory ./test/nightfox { minimal_init = './test/minimal_init.vim', sequential = true}"
