name: Tests
on:
  pull_request: ~
  push:
    paths:
      - "lua/*"
      - "test/*"
    branches:
      - main

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Neovim
        uses: MunifTanjim/setup-neovim-action@v1
        with:
          tag: nightly

      - name: Install plenary
        run: |
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim test/plenary

      - name: Run tests
        run: |
          nvim --version
          [ ! -d test ] && exit 0
          nvim --headless --noplugin -u test/minimal_init.vim -c "PlenaryBustedDirectory ./test/nightfox { minimal_init = './test/minimal_init.vim', sequential = true}"
